In [1]:
import dash 
from dash import ctx
import dash_bootstrap_components as dbc
import dash_html_components as html
import dash_core_components as dcc
from dash.dependencies import Input, Output, State
from dash_table import DataTable
from dash_canvas import DashCanvas
import dash_daq as daq
from jupyter_dash import JupyterDash

import plotly
import plotly.express as px
import plotly.io as pio
import plotly.graph_objs as go

import pandas as pd

import numpy as np

import json

<ipython-input-1-78da9870b458>:4: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
<ipython-input-1-78da9870b458>:5: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
<ipython-input-1-78da9870b458>:7: UserWarning:
The dash_table package is deprecated. Please replace
`import dash_table` with `from dash import dash_table`

Also, if you're using any of the table format helpers (e.g. Group), replace
`from dash_table.Format import Group` with
`from dash.dash_table.Format import Group`
  from dash_table import DataTable

In [10]:
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - LAYOUT - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #

website = dash.Dash(__name__,external_stylesheets=[dbc.themes.SOLAR],
                    meta_tags=[{"name":"viewport","content":"width=device-width, initial-scale=1.0"}],
                   suppress_callback_exceptions=True)

SIDEBAR_STYLE = {
    "position": "fixed",
    "top": 0,
    "left": 0,
    "bottom": 0,
    "width": "16rem",
    "padding": "2rem 1rem",
}

CONTENT_STYLE = {
    "margin-left": "18rem",
    "margin-right": "2rem",
    "padding": "2rem 1rem",
}

content = html.Div(id="page-content", children=[], style=CONTENT_STYLE)

sidebar = html.Div(
    [
        html.H2("Number recognition program", className="display-4",style={'textAlign':'center'}),
        html.Hr(),
        html.P(
            "EFMat final project", className="side"
        ),
        dbc.Nav(
            [
                dbc.NavLink("Description", href="/", active="exact"),
                dbc.NavLink("Statistics", href="/page-1", active="exact"),
                dbc.NavLink("Canvas board", href="/page-2", active="exact"),
            ],
            vertical=True,
            pills=True,
        ),
    ],
    style=SIDEBAR_STYLE,

)


website.layout=html.Div([
    dbc.Button("Success",color="success", className="mr-1"),
    dbc.Row(dbc.Col(html.Title("Number recognition project")
    ),),
    dcc.Location(id="url"),
    sidebar,
    content    
    ])


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - NRU - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #


columns=["width","height","path"]

allow=["number"]

NRU=dbc.Container([
    DataTable(id="drawn_table",columns=[{"name":i,"id":i}for i in columns])   
    
])

class NRU():
    def __int__(self, number, pre_drawn, user_drawn, entry):
        self.number=number
        self.pre_drawn=pre_drawn
        self.user_drawn=user_drawn
        self.entry=entry
    
    def comparison(self,pre_drawn,user_drawn):
        pass
    
    def frequency(self, number, entry):
        pass
        


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - CARDS - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #


card1=dbc.Container([
    dbc.CardHeader(   
    dbc.Button("Objective", id="objBtt",style={"color":"goldenrod"},className="text-dark btn-block align-middle w-100")
    ),
    dbc.Collapse(
    dbc.Card([
    dbc.CardBody([
        html.P("""This is the final project of UnB second semester EFMat course coordenated
                    by teacher Lucas Loureiro. Thus, subjects such as python Classes,
                    web development, and html, as well as the ones theached before,
                    were applied on this website. """,className="card-text")
        ],style={"color":"goldenrod"}),
    dbc.CardImg(src="https://lh3.googleusercontent.com/a-/AOh14GhKKmrBlYU4jgK88G7fFV3XLuyNgI4Le1Okj9Ve=s75-c",bottom=True)])
        ,id="objAns",is_open=False)])


card2=dbc.Container([
    dbc.CardHeader( 
    dbc.Button("Program explanation", id="pgmBtt",style={"color":"goldenrod"},className="text-dark btn-block align-middle w-100")),
    dbc.Collapse(
        dbc.Card([
    dbc.CardBody([
        html.P("""The general idea of the NRP (Number Recognition Program) is to possiblity the identification of a number drawn on a board. Hence, after the user drawn
                    a number on the board, the program will collect pixels that were painted and reshape them to a list with the intention of building a coordinate system. From that,
                    a comparison of the distance (10% of divergence is the initial tolerance) from predefined shapes of numbers will be done. Once the board was divided in four different quadrants, an 
                    analysis of the shape of the number writen on each quadrant become more precise, allowing more reliable results. According to the precision percentage,
                    a result will be declared. If the precision percentage is too low, tolerance percentage will be increased in 5% until a result above 80% be founded.\n\n
                    It is worth mentioning that since the program is based on pre defined parameters, it does not configure an AI.""",
               className="card-text")
        
    ],style={"color":"goldenrod"}),
        dbc.CardImg(src="https://th.bing.com/th/id/OIP.hmcZgKUKYsC_5rQB1SmY_AHaE7?pid=ImgDet&rs=1",
                    bottom=True)]),id="pgmAns",is_open=False)])


card3=dbc.Container([
    dbc.CardHeader(
    dbc.Button("Instructions",id="intBtt",style={"color":"goldenrod"},className="text-dark btn-block align-middle w-100")),
    dbc.Collapse(
    dbc.Card([
    dbc.CardBody([
        html.P("""First, click on 'Canvas board' in the sidebar. Second, drawn a single number number within the yellow image on the center of the page.
                    Finished the drawing, click on 'Analise' button below the board. If some mistake was done or an improvement on the drawing should 
                    be done, click on 'Clear' button below the board. Otherwise, just follow the previous step.\n\n
                    Finally, after clicking on 'Analise' button, the program will check your drawing and give you a result. 
                    Then, click on 'Right' or 'Wrong' button below the result. If you want to make another drawn, just click on the 'Clear' button to rerun the program.\n\n
                    You may like to check the performace of the program. For this reason, the "Statistics" button on the sidebar was created. There you will find the general 
                    precision of the program, individual precision for each number, and most frequent numbers. You just need to choose the number on the dropdown bar to display the graphs.
                    """,className="card-text")        
    ],style={"color":"goldenrod"}),dbc.CardImg(src="https://cdn0.iconfinder.com/data/icons/logistic-lineal-color/512/checklist-512.png",
                                               bottom=True)]),
        id="intAns",is_open=False)])

cards=dbc.Container([
                    dbc.Row([
                        dbc.Col(card1,width={"size":3,"offsett":0},xs=12,sm=12,md=12,lg=3,xl=3
                        ),                        

                        dbc.Col(card2,width={"size":4,"offsett":0},xs=12,sm=12,md=12,lg=4,xl=4
                        ),
                        
                        dbc.Col(card3,width={"size":4,"offsett":0},xs=12,sm=12,md=12,lg=4,xl=4
                        )
                    ],justify="around")                    
                ])


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - GRAPHS - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #


df1=pd.read_csv(r"C:\Users\adm\Documents\Jupyter\program_precision")
df2=pd.read_csv(r"C:\Users\adm\Documents\Jupyter\individual_precision")
df3=pd.read_csv(r"C:\Users\adm\Documents\Jupyter\number_frequence")

graph1=dbc.Container([
        dbc.Button(html.H1("General program precision", className="text-dark mb-4"),
                                className="badge-pill", style={"color":"goldenrod"}),
        dcc.Graph(id="idg1",figure={})
                    ])
                     
graph2=dbc.Container([
        dbc.Button(html.H1("Individual number precision", className="text-dark mb-4"),
                                className="badge-pill", style={"color":"goldenrod"}),
        dcc.Graph(id="idg2",figure={})
        
                    ])

graph3=dbc.Container([
        dbc.Button(html.H1("General number frequency", className="text-dark mb-4"),
                                className="badge-pill", style={"color":"goldenrod"}),
        dcc.Graph(id="idg3",figure={})        
                    ])

graphs=dbc.Container([        
    
        dbc.Row([
            dbc.Col([graph1],width={"size":4},xs=12,sm=12,md=12,lg=4,xl=4),
            dbc.Col([graph2],width={"size":4},xs=12,sm=12,md=12,lg=4,xl=4),
            dbc.Col([graph3],width={"size":4},xs=12,sm=12,md=12,lg=4,xl=4)
        ],justify="around")
])



# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - CANVAS - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #


file="assets\DrawingBackGround.PNG"

canvas=html.Div([
    dbc.Row([
        dbc.Col([
            DashCanvas(id='canvas_board',
               goButtonTitle ="Analize",
               width=150,height=400,
               hide_buttons=['line',"rectangle","pan",'zoom',"select","redo"],
               lineWidth=5,
               lineColor="#073642",
               filename=file
                      ),
            DataTable(id="drawn_table",columns=[{"name":i,"id":i} for i in columns])
        ],width={"size":5,"offset":5})
        ]),
    
    dbc.Row([
        html.Hr(),
        dbc.Col([html.H5("Choose the number drawn:"),
        dcc.Dropdown(
            id="dpdn",
            multi=False,
            value=0,
            options=[{"label":x,"value":x}for x in range(0,10)]),
                dbc.Button("Submit",id="sbm_btt",style={"color":"goldenrod"},
                           className="text-dark btn-block")],width={"size":3,"offset":0}
                )
],justify="center"),   
    
    dbc.Row([
        html.Hr(),
        dbc.Col([html.H5("Is the program's answer correct?",className="text-center")],width={"size":2}),
        dbc.Col([dbc.Button("YES",id="y_btt",style={"color":"goldenrod"},className="text-dark btn-block")],width={"size":1}),
        dbc.Col([dbc.Button("NO",id="n_btt",style={"color":"goldenrod"},className="text-dark btn-block")],width={"size":1,"offset":0})
        
    ],justify="center")
    
])    



# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - CALLBACKS - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - COORDENATION - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #


@website.callback(
    Output("page-content", "children"),
    [Input("url", "pathname")]
)

def page_content(pathname):
    if pathname == "/":
        return [
                html.H1('PROJECT DESCRIPTION',
                        style={'textAlign':'center',"color":"goldenrod"}, className="mb-4"),
                cards
                
                ]
    elif pathname == "/page-1":
        return [
                html.H1('Program statistics',
                        style={'textAlign':'center',"color":"goldenrod"},className="mb-4"),
                graphs
                
                ]
    elif pathname == "/page-2":
        return [

                html.H1('CANVAS BOARD',
                style={'textAlign':'center',"color":"goldenrod"},className="mb-4"),

                html.H5("""Drawn the number inside the canvas.
                    Make sure to drawn the number on the center and as big as possible.""",
                    style={'textAlign':'center'}), canvas        
                ]
    
    
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - CARDS COLAPSE - - - - - - - - - - - - - - - - - - - - - - - - - - #     
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #


@website.callback(Output("objAns","is_open"),
                  [Input("objBtt","n_clicks")],
                  [State("objAns","is_open")],
                 )
def toggle_collapse(n,is_open):
    if n:
        return not is_open
    return is_open


@website.callback(Output("pgmAns","is_open"),
                  [Input("pgmBtt","n_clicks")],
                  [State("pgmAns","is_open")],
                 )
def toggle_collapse(n,is_open):
    if n:
        return not is_open
    return is_open


@website.callback(Output("intAns","is_open"),
                  [Input("intBtt","n_clicks")],
                  [State("intAns","is_open")],
                 )
def toggle_collapse(n,is_open):
    if n:
        return not is_open
    return is_open

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - GRAPHS - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #


"""
@website.callback(Output("idg3","children"),
                 [Intput("result","n_clicks"),Input("number","text")])

def update_graph(clicks):
    if clicks:
        df
"""


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - DRAWING DATA - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #

@website.callback(Output("drawn_table","data"),Input("canvas_board", "json_data"))
def drawn_data(string):
    
    if string:
        data=json.loads(string)

        lstx=[]
        lsty=[]
        for i in range(1,len(data["objects"][1]["path"])-1):
            
            lstx.append(data["objects"][1]["path"][i][1])
            lstx.append(data["objects"][1]["path"][i][3])
            lsty.append(data["objects"][1]["path"][i][2])
            lsty.append(data["objects"][1]["path"][i][4])
            
        preguiçax=data["objects"][1]["width"]
        preguiçay=data["objects"][1]["height"]
        NTP_draw(lstx,lsty,preguiçax,preguiçay)
        fig=NTP_draw(lstx,lsty,preguiçax,preguiçay)[0]
        dfff=NTP_draw(lstx,lsty,preguiçax,preguiçay)[1]
        stddx=NTP_draw(lstx,lsty,preguiçax,preguiçay)[2]
        stddy=NTP_draw(lstx,lsty,preguiçax,preguiçay)[3]
        inf_limit=0.6
        upper_limit=1.5
        NRP_base(fig,preguiçax,preguiçay,df,dfff,stddx,stddy,inf_limit,upper_limit)


    else:
        raise PreventUpdate
    return data['objects'][1:]


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - CANVAS RES - - - - - - - - - - - - - - - - - - - - - - - - - - #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #


@website.callback(
    Output("idg1","figure"),
    [Input("y_btt","n_clicks"),
     Input("n_btt","n_clicks")],
)
def trig1 (n1,n2):
    
    triggered_id=ctx.triggered_id
    
    print(type(triggered_id))
    
    if triggered_id=="y_btt":
        df1.loc[0,"Final"]= df1.loc[0,"Final"]+1
        df1[0,"Precision"]=df1[0,"Final"]/sum(df1["Final"])
        df1[1,"Precision"]=df1[1,"Final"]/sum(df1["Final"])
        bar1=px.bar(data_frame=df1,
           x="Result",y="Precision",
            orientation="v", color_discrete_sequence=["goldenrod"],
           )
        bar1.update_layout(paper_bgcolor="#002b36",plot_bgcolor="#002b36")
        
        return bar1
    
    elif triggered_id=="n_btt":
        df1.loc[1,"Final"]= df1.loc[1,"Final"]+1
        df1[0,"Precision"]=df1[0,"Final"]/sum(df1["Final"])
        df1[1,"Precision"]=df1[1,"Final"]/sum(df1["Final"])
        bar1=px.bar(data_frame=df1,
           x="Result",y="Precision",
            orientation="v", color_discrete_sequence=["goldenrod"],
           )
        bar1.update_layout(paper_bgcolor="#002b36",plot_bgcolor="#002b36")
        return bar1
    
    else:
        df1[0,"Precision"]=df1[0,"Final"]/sum(df1["Final"])
        df1[1,"Precision"]=df1[1,"Final"]/sum(df1["Final"])
        bar1=px.bar(data_frame=df1,
           x="Result",y="Precision",
            orientation="v", color_discrete_sequence=["goldenrod"],
           )
        bar1.update_layout(paper_bgcolor="#002b36",plot_bgcolor="#002b36")
        
        return bar1

    
@website.callback(
    Output("idg2","figure"),
    [Input("y_btt","n_clicks"),Input("n_btt","n_clicks")],
    [State("dpdn","value")],
)
def trig2 (yb,nb,value):

    button_clicked = ctx.triggered_id
    print(button_clicked)
    
    if not button_clicked:
        
        df2.loc[value,"Precision"]=df2.loc[value,"Right"]/df2.loc[value,"Total"]
        
        bar2=px.bar(data_frame=df2,
           x="Numbers",y="Precision",
            orientation="v", color_discrete_sequence=["goldenrod"], labels={"Precision":"Precision in %"}
           )
        bar2.update_layout(paper_bgcolor="#002b36",plot_bgcolor="#002b36")

        
        return bar2
    
    elif button_clicked=="y_btt":
        
        df2.loc[value,"Total"]=df2.loc[value,"Total"]+1
        df2.loc[value,"Right"]=df2.loc[value,"Right"]+1
        df2.loc[value,"Precision"]=df2.loc[value,"Right"]/df2.loc[value,"Total"]
        
        bar2=px.bar(data_frame=df2,
           x="Numbers",y="Precision",
            orientation="v", color_discrete_sequence=["goldenrod"], labels={"Precision":"Precision in %"}
           )
        bar2.update_layout(paper_bgcolor="#002b36",plot_bgcolor="#002b36")

        return bar2
    
    elif button_clicked=="n_btt":
        
        df2.loc[value,"Total"]=df2.loc[value,"Total"]+1
        df2.loc[value,"Precision"]=df2.loc[value,"Right"]/df2.loc[value,"Total"]
        
        bar2=px.bar(data_frame=df2,
           x="Numbers",y="Precision",
            orientation="v", color_discrete_sequence=["goldenrod"], labels={"Precision":"Precision in %"}
           )
        bar2.update_layout(paper_bgcolor="#002b36",plot_bgcolor="#002b36")

        return bar2
    
@website.callback(
    Output("idg3","figure"),
    [Input("sbm_btt","n_clicks")],
    [State("dpdn","value")],
)
def trig3 (n,value):
    df3.loc[value,"Frequence"]= df3.loc[value,"Frequence"]+1
    bar3=px.bar(data_frame=df3,
       x="Numbers",y="Frequence",
        orientation="v", color_discrete_sequence=["goldenrod"], labels={"Frequence":"Frequency in %"}
       )
    bar3.update_layout(paper_bgcolor="#002b36",plot_bgcolor="#002b36")

    return bar3


# Não está podendo ativar o debug, caso contrário, a página cai. O flask considera o site como "de produção".
# O código abaixo serviria para corrigir isso e permitir o debug=True.
website.run_server(debug=False)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4850.579579,-0.568109,NaN,NaN,100,0.656716,"[4.58257569495584, 6.363961030678928, 2.039607...",1.710699,"[1.0198039027185568, 4.388621651498338, 6.7195...",1.896095,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4850.579579,-0.568109,NaN,NaN,100,0.656716,"[4.58257569495584, 6.363961030678928, 2.039607...",1.710699,"[1.0198039027185568, 4.388621651498338, 6.7195...",1.896095,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4850.579579,-0.568109,NaN,NaN,100,0.656716,"[4.58257569495584, 6.363961030678928, 2.039607...",1.710699,"[1.0198039027185568, 4.388621651498338, 6.7195...",1.896095,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4850.579579,-0.568109,NaN,NaN,100,0.656716,"[4.58257569495584, 6.363961030678928, 2.039607...",1.710699,"[1.0198039027185568, 4.388621651498338, 6.7195...",1.896095,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4850.579579,-0.568109,NaN,NaN,100,0.656716,"[4.58257569495584, 6.363961030678928, 2.039607...",1.710699,"[1.0198039027185568, 4.388621651498338, 6.7195...",1.896095,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,6392.109468,-1.070491,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.23591549295774647, -0.47183098591549...","[2.7207943239739403, 3.4769725420481365, 3.624...",1.649775,"[3.6282905404103194, 0.8207099298440861, 2.777...",1.822852
num1,3709.328517,8.011979,114,0.230333,"[[0.0, 0.0, 0.0, 1.6923076923076923, 3.3846153...","[[0.0, -0.2967753366406804, -0.593550673281360...","[3.3547634595933116, 5.7625602462547825, 2.368...",1.799602,"[2.591444106869923, 3.25436767718572, 1.943278...",1.694630
num2,1750.463122,1.506730,90,0.819789,"[[0.0, 0.0, 0.0, 0.5649717514124294, 1.1299435...","[[0.0, -0.7052631578947368, -1.410526315789473...","[1.7688641310239008, 2.6765857633807713, 2.786...",2.112329,"[3.714997605524905, 2.782147255899745, 0.32309...",2.486040
num3,9662.564284,0.903102,250,0.312883,"[[0.0, 0.0, 0.0, 0.43137254901960786, 0.862745...","[[0.0, -0.20552147239263804, -0.41104294478527...","[5.31344527153473, 8.070721011122208, 1.439931...",2.419202,"[0.4022344530662967, 1.2018771998389821, 3.098...",1.007250
num4,11894.677808,1.031719,290,0.464286,"[[0.0, 0.28205128205128205, 0.5641025641025641...","[[0.0, 0.0, 0.0, 0.19940476190476192, 0.398809...","[0.31334932029965895, 0.27440158404301457, 9.0...",2.701479,"[6.024081869091995, 3.3179801492935166, 0.6840...",2.458827
num5,6637.019908,-0.726662,174,0.426667,"[[0.0, -0.34375, -0.6875, -1.03125, -1.375, -2...","[[0.0, 0.0, 0.0, 0.22333333333333333, 0.446666...","[7.694405445659672, 3.865888802982339, 1.32903...",2.251320,"[0.56291259377926, 0.4566022989011158, 4.29148...",1.616189
num6,13572.409306,-0.386711,326,0.434783,"[[0.0, -0.3142857142857143, -0.628571428571428...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.2080745341614907,...","[3.5001647874837003, 4.511180042547128, 2.0322...",1.848244,"[2.048471068518741, 3.293132849272065, 4.22184...",1.360473
num7,6707.680548,1.138720,206,0.677419,"[[0.0, 0.20952380952380953, 0.4190476190476190...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[4.187384573831379, 4.372777465917962, 2.88144...",1.246562,"[0.0, 0.0, 0.36979544785871, 0.518146535707980...",1.623530
num8,11116.362977,-0.851355,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.328358...","[[0.0, -0.20303030303030303, -0.40606060606060...","[8.109849515672428, 6.229298104114171, 4.54302...",2.516114,"[2.229114185988454, 3.207145941829397, 5.79530...",1.259508
num9,4037.700880,-0.724820,146,0.410596,"[[0.0, 0.0, 0.0, -1.064516129032258, -2.129032...","[[0.0, -0.44370860927152317, -0.88741721854304...","[6.156899762285776, 6.2178963759126145, 0.8031...",2.739534,"[0.5267699145155356, 2.475795776662022, 4.0394...",2.722674

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            2            3
1     1            0            0
2     2            0            0
3     3            0            0
4     4            0            0
5     5            2            3
6     6            6            4
7     7            0            0
8     8            4            4
9     9            3            1

   nums  percentage
0     0           0
1     1           0
2     2           0
3     3           0
4     4           0
5     5           3
6     6           4
7     7           0
8     8           2
9     9           2

127.0.0.1 - - [17/Jun/2022 17:04:01] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [6, 8, 9]
FinalStanDevy  [0, 5, 6, 8]
FinalRatio  [5, 6, 8, 9]
Partial result[6, 8, 9, 0, 5]
Final result med --> 6

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,6968.288689,-0.449803,NaN,NaN,112,0.56383,"[4.152565671111363, 8.31035399192323, 3.486692...",2.533946,"[1.3787046261911908, 5.9363009881143665, 8.009...",2.140146,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,6968.288689,-0.449803,NaN,NaN,112,0.56383,"[4.152565671111363, 8.31035399192323, 3.486692...",2.533946,"[1.3787046261911908, 5.9363009881143665, 8.009...",2.140146,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,6968.288689,-0.449803,NaN,NaN,112,0.56383,"[4.152565671111363, 8.31035399192323, 3.486692...",2.533946,"[1.3787046261911908, 5.9363009881143665, 8.009...",2.140146,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,6968.288689,-0.449803,NaN,NaN,112,0.56383,"[4.152565671111363, 8.31035399192323, 3.486692...",2.533946,"[1.3787046261911908, 5.9363009881143665, 8.009...",2.140146,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,6968.288689,-0.449803,NaN,NaN,112,0.56383,"[4.152565671111363, 8.31035399192323, 3.486692...",2.533946,"[1.3787046261911908, 5.9363009881143665, 8.009...",2.140146,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,8314.786523,-0.919080,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.33098591549295775, -0.66197183098591...","[3.2773204356958825, 4.188171471103436, 4.3664...",1.987229,"[5.0904374746055225, 1.1514437821693144, 3.896...",2.557434
num1,4480.259139,6.878757,114,0.230333,"[[0.0, 0.0, 0.0, 2.0384615384615383, 4.0769230...","[[0.0, -0.41637136782423817, -0.83274273564847...","[4.040965076328307, 6.9412657511705325, 2.8528...",2.167702,"[3.6357574036682503, 4.565829278439667, 2.7263...",2.377540
num2,2220.506564,1.293616,90,0.819789,"[[0.0, 0.0, 0.0, 0.6805341551104264, 1.3610683...","[[0.0, -0.9894736842105263, -1.978947368421052...","[2.1306772487333356, 3.224069214981384, 3.3569...",2.544397,"[5.2120861928259865, 3.9033110754414335, 0.453...",3.487876
num3,12730.867529,0.775367,250,0.312883,"[[0.0, 0.0, 0.0, 0.5196078431372549, 1.0392156...","[[0.0, -0.2883435582822086, -0.576687116564417...","[6.4002863498031966, 9.72155030885175, 1.73446...",2.914039,"[0.5643289341527148, 1.6862157729084226, 4.346...",1.413157
num4,15515.931835,0.885792,290,0.464286,"[[0.0, 0.33974358974358976, 0.6794871794871795...","[[0.0, 0.0, 0.0, 0.27976190476190477, 0.559523...","[0.3774434994518619, 0.33052918077908566, 10.9...",3.254054,"[8.451696950666381, 4.655076627367023, 0.95976...",3.449698
num5,8878.632056,-0.623882,174,0.426667,"[[0.0, -0.4140625, -0.828125, -1.2421875, -1.6...","[[0.0, 0.0, 0.0, 0.31333333333333335, 0.626666...","[9.268261104999151, 4.656638785410545, 1.60088...",2.711817,"[0.7897579673917976, 0.6406062103985805, 6.020...",2.267489
num6,18713.459453,-0.332014,326,0.434783,"[[0.0, -0.37857142857142856, -0.75714285714285...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.2919254658385093,...","[4.216107584923548, 5.4339214148863135, 2.4479...",2.226293,"[2.873974334936741, 4.62021623629215, 5.923192...",1.908724
num7,8684.380541,0.977658,206,0.677419,"[[0.0, 0.2523809523809524, 0.5047619047619047,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[5.043895054842342, 5.267209220310272, 3.47083...",1.501540,"[0.0, 0.0, 0.5188174940107275, 0.7269518560679...",2.277788
num8,14709.462048,-0.730938,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.395522...","[[0.0, -0.28484848484848485, -0.56969696969696...","[9.768682371150877, 7.503472716319342, 5.47227...",3.030773,"[3.127413932580816, 4.499577888536766, 8.13072...",1.767071
num9,5402.305104,-0.622300,146,0.410596,"[[0.0, 0.0, 0.0, -1.282258064516129, -2.564516...","[[0.0, -0.6225165562913907, -1.245033112582781...","[7.41626562275332, 7.489738816440194, 0.967370...",3.299893,"[0.7390503278277665, 3.4735045224810457, 5.667...",3.819871

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            4            2
1     1            0            0
2     2            0            0
3     3            0            0
4     4            0            0
5     5            5            4
6     6            5            7
7     7            0            0
8     8            2            7
9     9            1            5

   nums  percentage
0     0           0
1     1           0
2     2           0
3     3           0
4     4           0
5     5           4
6     6           3
7     7           0
8     8           3
9     9           3

127.0.0.1 - - [17/Jun/2022 17:04:12] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [0, 5, 6]
FinalStanDevy  [6, 8, 9]
FinalRatio  [5, 6, 8, 9]
Partial result[5, 6, 8, 9]
Final result med --> 6

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,1517.380144,1.744864,NaN,NaN,78,0.265957,"[0.749149177264394, 2.0, 3.0, 1.02519286388623...",0.976464,"[1.265717510476382, 3.0220279716151683, 3.5757...",3.154289,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,1517.380144,1.744864,NaN,NaN,78,0.265957,"[0.749149177264394, 2.0, 3.0, 1.02519286388623...",0.976464,"[1.265717510476382, 3.0220279716151683, 3.5757...",3.154289,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,1517.380144,1.744864,NaN,NaN,78,0.265957,"[0.749149177264394, 2.0, 3.0, 1.02519286388623...",0.976464,"[1.265717510476382, 3.0220279716151683, 3.5757...",3.154289,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,1517.380144,1.744864,NaN,NaN,78,0.265957,"[0.749149177264394, 2.0, 3.0, 1.02519286388623...",0.976464,"[1.265717510476382, 3.0220279716151683, 3.5757...",3.154289,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,1517.380144,1.744864,NaN,NaN,78,0.265957,"[0.749149177264394, 2.0, 3.0, 1.02519286388623...",0.976464,"[1.265717510476382, 3.0220279716151683, 3.5757...",3.154289,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,6672.457368,-0.433528,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.33098591549295775, -0.66197183098591...","[1.545905865894284, 1.975552580709168, 2.05963...",0.937372,"[5.0904374746055225, 1.1514437821693144, 3.896...",2.557434
num1,2188.415924,3.244697,114,0.230333,"[[0.0, 0.0, 0.0, 0.9615384615384616, 1.9230769...","[[0.0, -0.41637136782423817, -0.83274273564847...","[1.9061156020416545, 3.2741819580993083, 1.345...",1.022501,"[3.6357574036682503, 4.565829278439667, 2.7263...",2.377540
num2,1590.916528,0.610196,90,0.819789,"[[0.0, 0.0, 0.0, 0.32100667693888035, 0.642013...","[[0.0, -0.9894736842105263, -1.978947368421052...","[1.005036438081762, 1.5207873655572566, 1.5834...",1.200187,"[5.2120861928259865, 3.9033110754414335, 0.453...",3.487876
num3,10712.667741,0.365739,250,0.312883,"[[0.0, 0.0, 0.0, 0.24509803921568626, 0.490196...","[[0.0, -0.2883435582822086, -0.576687116564417...","[3.0190029951901867, 4.585636938137618, 0.8181...",1.374547,"[0.5643289341527148, 1.6862157729084226, 4.346...",1.413157
num4,12587.665059,0.417826,290,0.464286,"[[0.0, 0.16025641025641027, 0.3205128205128205...","[[0.0, 0.0, 0.0, 0.27976190476190477, 0.559523...","[0.17803938653389714, 0.15590999093353103, 5.1...",1.534931,"[8.451696950666381, 4.655076627367023, 0.95976...",3.449698
num5,7852.258738,-0.294284,174,0.426667,"[[0.0, -0.1953125, -0.390625, -0.5859375, -0.7...","[[0.0, 0.0, 0.0, 0.31333333333333335, 0.626666...","[4.371821275942996, 2.196527728967238, 0.75513...",1.279159,"[0.7897579673917976, 0.6406062103985805, 6.020...",2.267489
num6,17976.642653,-0.156611,326,0.434783,"[[0.0, -0.17857142857142858, -0.35714285714285...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.2919254658385093,...","[1.988729992888466, 2.5631704787199596, 1.1546...",1.050138,"[2.873974334936741, 4.62021623629215, 5.923192...",1.908724
num7,6838.264285,0.461160,206,0.677419,"[[0.0, 0.11904761904761904, 0.2380952380952380...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[2.3791957805860107, 2.4845326510897507, 1.637...",0.708274,"[0.0, 0.0, 0.5188174940107275, 0.7269518560679...",2.277788
num8,12561.356518,-0.344782,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.186567...","[[0.0, -0.28484848484848485, -0.56969696969696...","[4.607869042995698, 3.539373922792142, 2.58126...",1.429610,"[3.127413932580816, 4.499577888536766, 8.13072...",1.767071
num9,4780.224879,-0.293538,146,0.410596,"[[0.0, 0.0, 0.0, -0.6048387096774193, -1.20967...","[[0.0, -0.6225165562913907, -1.245033112582781...","[3.4982385012987356, 3.532895668132166, 0.4563...",1.556554,"[0.7390503278277665, 3.4735045224810457, 5.667...",3.819871

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

invalid value encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            0            0
1     1            3            7
2     2            3            5
3     3            0            3
4     4            1            1
5     5            0            0
6     6            0            0
7     7            2            4
8     8            0            0
9     9            0            0

<ipython-input-9-a6f701c671c7>:358: RuntimeWarning:

divide by zero encountered in double_scalars

   nums  percentage
0     0           0
1     1           4
2     2           2
3     3           0
4     4           2
5     5           0
6     6           0
7     7           0
8     8           0
9     9           0

127.0.0.1 - - [17/Jun/2022 17:04:19] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [1, 2, 7]
FinalStanDevy  [1, 2, 7]
FinalRatio  [1, 2, 4]
Partial result[1, 2, 7]
Final result med --> 1

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3682.445689,1.020369,NaN,NaN,110,0.637681,"[3.0922457003081725, 4.088888389827094, 4.4531...",1.564608,"[2.7716093126229358, 0.7820295697311479, 0.440...",2.277765,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3682.445689,1.020369,NaN,NaN,110,0.637681,"[3.0922457003081725, 4.088888389827094, 4.4531...",1.564608,"[2.7716093126229358, 0.7820295697311479, 0.440...",2.277765,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3682.445689,1.020369,NaN,NaN,110,0.637681,"[3.0922457003081725, 4.088888389827094, 4.4531...",1.564608,"[2.7716093126229358, 0.7820295697311479, 0.440...",2.277765,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3682.445689,1.020369,NaN,NaN,110,0.637681,"[3.0922457003081725, 4.088888389827094, 4.4531...",1.564608,"[2.7716093126229358, 0.7820295697311479, 0.440...",2.277765,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3682.445689,1.020369,NaN,NaN,110,0.637681,"[3.0922457003081725, 4.088888389827094, 4.4531...",1.564608,"[2.7716093126229358, 0.7820295697311479, 0.440...",2.277765,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,6481.724314,-1.039462,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.24295774647887325, -0.48591549295774...","[2.7207943239739403, 3.4769725420481365, 3.624...",1.649775,"[3.736597720721076, 0.8452087337200291, 2.8600...",1.877266
num1,3711.051935,7.779748,114,0.230333,"[[0.0, 0.0, 0.0, 1.6923076923076923, 3.3846153...","[[0.0, -0.3056343019135365, -0.611268603827073...","[3.3547634595933116, 5.7625602462547825, 2.368...",1.799602,"[2.668800647373503, 3.351512980982308, 2.00128...",1.745216
num2,1766.605428,1.463056,90,0.819789,"[[0.0, 0.0, 0.0, 0.5649717514124294, 1.1299435...","[[0.0, -0.7263157894736842, -1.452631578947368...","[1.7688641310239008, 2.6765857633807713, 2.786...",2.112329,"[3.8258930564360965, 2.865196427717649, 0.3327...",2.560250
num3,9822.477402,0.876925,250,0.312883,"[[0.0, 0.0, 0.0, 0.43137254901960786, 0.862745...","[[0.0, -0.2116564417177914, -0.423312883435582...","[5.31344527153473, 8.070721011122208, 1.439931...",2.419202,"[0.4142414516652907, 1.2377541311774591, 3.190...",1.037317
num4,12067.972993,1.001815,290,0.464286,"[[0.0, 0.28205128205128205, 0.5641025641025641...","[[0.0, 0.0, 0.0, 0.20535714285714285, 0.410714...","[0.31334932029965895, 0.27440158404301457, 9.0...",2.701479,"[6.203905208467876, 3.417024332854517, 0.70450...",2.532225
num5,6767.332271,-0.705599,174,0.426667,"[[0.0, -0.34375, -0.6875, -1.03125, -1.375, -2...","[[0.0, 0.0, 0.0, 0.23, 0.46, 0.690000000000000...","[7.694405445659672, 3.865888802982339, 1.32903...",2.251320,"[0.5797159547875961, 0.4702322182712984, 4.419...",1.664433
num6,13925.516914,-0.375502,326,0.434783,"[[0.0, -0.3142857142857143, -0.628571428571428...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.21428571428571427...","[3.5001647874837003, 4.511180042547128, 2.0322...",1.848244,"[2.109619458623778, 3.3914353223846634, 4.3478...",1.401085
num7,6795.587680,1.105713,206,0.677419,"[[0.0, 0.20952380952380953, 0.4190476190476190...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[4.187384573831379, 4.372777465917962, 2.88144...",1.246562,"[0.0, 0.0, 0.3808341179440447, 0.5336135964753...",1.671993
num8,11309.937050,-0.826678,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.328358...","[[0.0, -0.20909090909090908, -0.41818181818181...","[8.109849515672428, 6.229298104114171, 4.54302...",2.516114,"[2.295654907958258, 3.302881641585498, 5.96829...",1.297105
num9,4117.115427,-0.703810,146,0.410596,"[[0.0, 0.0, 0.0, -1.064516129032258, -2.129032...","[[0.0, -0.45695364238410596, -0.91390728476821...","[6.156899762285776, 6.2178963759126145, 0.8031...",2.739534,"[0.542494389575701, 2.5497001282041722, 4.1600...",2.803948

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            0            0
1     1            2            4
2     2            5            6
3     3            3            2
4     4            0            3
5     5            0            0
6     6            0            0
7     7            4            3
8     8            0            0
9     9            0            0

<ipython-input-9-a6f701c671c7>:358: RuntimeWarning:

divide by zero encountered in double_scalars

   nums  percentage
0     0           0
1     1           1
2     2           2
3     3           1
4     4           2
5     5           0
6     6           0
7     7           1
8     8           0
9     9           0

127.0.0.1 - - [17/Jun/2022 17:04:24] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [2, 3, 7]
FinalStanDevy  [1, 2, 4, 7]
FinalRatio  [2]
Partial result[2, 1, 4, 7]
Final result med --> 2

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4310.71392,0.666806,NaN,NaN,116,0.42869,"[5.2373420803033, 4.904880349169531, 0.6680426...",1.967788,"[0.9791208740244552, 1.3560394445614816, 4.762...",1.396077,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4310.71392,0.666806,NaN,NaN,116,0.42869,"[5.2373420803033, 4.904880349169531, 0.6680426...",1.967788,"[0.9791208740244552, 1.3560394445614816, 4.762...",1.396077,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4310.71392,0.666806,NaN,NaN,116,0.42869,"[5.2373420803033, 4.904880349169531, 0.6680426...",1.967788,"[0.9791208740244552, 1.3560394445614816, 4.762...",1.396077,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4310.71392,0.666806,NaN,NaN,116,0.42869,"[5.2373420803033, 4.904880349169531, 0.6680426...",1.967788,"[0.9791208740244552, 1.3560394445614816, 4.762...",1.396077,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4310.71392,0.666806,NaN,NaN,116,0.42869,"[5.2373420803033, 4.904880349169531, 0.6680426...",1.967788,"[0.9791208740244552, 1.3560394445614816, 4.762...",1.396077,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,6673.994790,-0.698794,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.29577464788732394, -0.59154929577464...","[2.2267228092341265, 2.8455859372534853, 2.966...",1.350191,"[4.548901573051745, 1.0289497627896005, 3.4818...",2.285367
num1,3066.944693,5.230049,114,0.230333,"[[0.0, 0.0, 0.0, 1.385, 2.77, 3.4625, 4.155, 4...","[[0.0, -0.3720765414599575, -0.744153082919915...","[2.7455689131807985, 4.716131692446243, 1.9383...",1.472810,"[3.2489747011503516, 4.080102759456723, 2.4363...",2.124611
num2,1702.211414,0.983561,90,0.819789,"[[0.0, 0.0, 0.0, 0.46237801746276325, 0.924756...","[[0.0, -0.8842105263157894, -1.768421052631579...","[1.44765448541297, 2.190542121348672, 2.280856...",1.728750,"[4.657608938270029, 3.4880652163519192, 0.4050...",3.116826
num3,10436.587244,0.589526,250,0.312883,"[[0.0, 0.0, 0.0, 0.3530392156862745, 0.7060784...","[[0.0, -0.25766871165644173, -0.51533742331288...","[4.348571914271945, 6.605151445693425, 1.17845...",1.979897,"[0.5042939411577452, 1.5068311162160373, 3.884...",1.262821
num4,12513.395587,0.673484,290,0.464286,"[[0.0, 0.2308333333333333, 0.4616666666666666,...","[[0.0, 0.0, 0.0, 0.25, 0.5, 1.25, 2.0, 2.75, 3...","[0.2564479323634254, 0.22457275094065807, 7.41...",2.210915,"[7.552580253786979, 4.15985570956202, 0.857661...",3.082709
num5,7450.405758,-0.474350,174,0.426667,"[[0.0, -0.281328125, -0.56265625, -0.843984375...","[[0.0, 0.0, 0.0, 0.28, 0.56, 0.840000000000000...","[6.297171365868291, 3.16387854080441, 1.087692...",1.842501,"[0.705741162350117, 0.5724566135476677, 5.3803...",2.026267
num6,16368.651102,-0.252437,326,0.434783,"[[0.0, -0.2572142857142857, -0.514428571428571...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.2608695652173913,...","[2.8645666817565463, 3.6919907575482287, 1.663...",1.512619,"[2.5682323844115555, 4.128703870729155, 5.2930...",1.705668
num7,6914.297931,0.743332,206,0.677419,"[[0.0, 0.17147619047619048, 0.3429523809523809...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[3.42699360235609, 3.578720830629677, 2.358202...",1.020197,"[0.0, 0.0, 0.4636241435840544, 0.6496165522309...",2.035470
num8,12140.674239,-0.555746,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.268731...","[[0.0, -0.2545454545454545, -0.509090909090909...","[6.637174569531002, 5.098114198389801, 3.71805...",2.059210,"[2.7947103227317927, 4.0208993897562575, 7.265...",1.579084
num9,4534.393696,-0.473147,146,0.410596,"[[0.0, 0.0, 0.0, -0.8712096774193548, -1.74241...","[[0.0, -0.5562913907284768, -1.112582781456953...","[5.038862737270699, 5.0887829203775725, 0.6572...",2.242060,"[0.6604279525269401, 3.103982764770296, 5.0643...",3.413502

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            0            0
1     1            2            1
2     2            0            1
3     3            4            6
4     4            0            2
5     5            0            0
6     6            0            0
7     7            3            3
8     8            0            0
9     9            0            0

<ipython-input-9-a6f701c671c7>:358: RuntimeWarning:

divide by zero encountered in double_scalars

   nums  percentage
0     0           0
1     1           2
2     2           0
3     3           4
4     4           3
5     5           0
6     6           0
7     7           1
8     8           0
9     9           0

127.0.0.1 - - [17/Jun/2022 17:04:30] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [1, 3, 7]
FinalStanDevy  [3, 4, 7]
FinalRatio  [1, 3, 4]
Partial result[1, 3, 4, 7]
Final result med --> 3

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3806.365491,0.838992,NaN,NaN,104,0.563301,"[0.0, 0.0, 1.4966629547095764, 5.5731499172371...",1.774762,"[6.365728552176884, 6.343500610861482, 1.07238...",3.473738,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3806.365491,0.838992,NaN,NaN,104,0.563301,"[0.0, 0.0, 1.4966629547095764, 5.5731499172371...",1.774762,"[6.365728552176884, 6.343500610861482, 1.07238...",3.473738,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3806.365491,0.838992,NaN,NaN,104,0.563301,"[0.0, 0.0, 1.4966629547095764, 5.5731499172371...",1.774762,"[6.365728552176884, 6.343500610861482, 1.07238...",3.473738,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3806.365491,0.838992,NaN,NaN,104,0.563301,"[0.0, 0.0, 1.4966629547095764, 5.5731499172371...",1.774762,"[6.365728552176884, 6.343500610861482, 1.07238...",3.473738,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3806.365491,0.838992,NaN,NaN,104,0.563301,"[0.0, 0.0, 1.4966629547095764, 5.5731499172371...",1.774762,"[6.365728552176884, 6.343500610861482, 1.07238...",3.473738,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,6278.504972,-0.918218,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.25003521126760564, -0.50007042253521...","[2.473449385430855, 3.160884129134669, 3.29541...",1.499795,"[3.8454464369333854, 0.8698300316153513, 2.943...",1.931951
num1,3381.393383,6.872305,114,0.230333,"[[0.0, 0.0, 0.0, 1.5384615384615385, 3.0769230...","[[0.0, -0.31453756201275695, -0.62907512402551...","[3.049784963266647, 5.238691132958893, 2.15311...",1.636001,"[2.746543970579601, 3.44914401129788, 2.059585...",1.796055
num2,1676.442691,1.292403,90,0.819789,"[[0.0, 0.0, 0.0, 0.5136106831022086, 1.0272213...","[[0.0, -0.7474736842105264, -1.494947368421052...","[1.6080583009308191, 2.433259784891611, 2.5335...",1.920299,"[3.9373429846018437, 2.948660845394641, 0.3424...",2.634831
num3,9613.836490,0.774639,250,0.312883,"[[0.0, 0.0, 0.0, 0.39215686274509803, 0.784313...","[[0.0, -0.21782208588957055, -0.43564417177914...","[4.830404792304299, 7.337019101020188, 1.30902...",2.199275,"[0.4263084852572796, 1.2738104471726286, 3.283...",1.067535
num4,11716.298796,0.884961,290,0.464286,"[[0.0, 0.2564102564102564, 0.5128205128205128,...","[[0.0, 0.0, 0.0, 0.21133928571428573, 0.422678...","[0.2848630184542354, 0.24945598549364953, 8.23...",2.455890,"[6.384627664540635, 3.516563737333323, 0.72502...",2.605990
num5,6705.383360,-0.623297,174,0.426667,"[[0.0, -0.3125, -0.625, -0.9375, -1.25, -2.187...","[[0.0, 0.0, 0.0, 0.23670000000000002, 0.473400...","[6.994914041508794, 3.514444366347581, 1.20821...",2.046654,"[0.5966033326009739, 0.48393028723833187, 4.54...",1.712919
num6,14135.309106,-0.331703,326,0.434783,"[[0.0, -0.2857142857142857, -0.571428571428571...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.22052795031055902...","[3.1819679886215457, 4.101072765951934, 1.8475...",1.680221,"[2.1710735906793404, 3.4902293078628257, 4.474...",1.441899
num7,6557.396354,0.976741,206,0.677419,"[[0.0, 0.19047619047619047, 0.3809523809523809...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[3.8067132489376174, 3.9752522417436014, 2.619...",1.133238,"[0.0, 0.0, 0.391927981379806, 0.54915799254662...",1.720699
num8,11108.274966,-0.730253,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.298507...","[[0.0, -0.2151818181818182, -0.430363636363636...","[7.372590468793115, 5.662998276467428, 4.13002...",2.287376,"[2.362528333537912, 3.39909601984038, 6.142154...",1.334890
num9,4079.971022,-0.621717,146,0.410596,"[[0.0, 0.0, 0.0, -0.967741935483871, -1.935483...","[[0.0, -0.4702649006622517, -0.940529801324503...","[5.597181602077977, 5.652633069011466, 0.73009...",2.490486,"[0.558297487011167, 2.623974001504033, 4.28118...",2.885628

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

invalid value encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            0            0
1     1            1            2
2     2            0            2
3     3            3            2
4     4            0            4
5     5            0            0
6     6            0            0
7     7            2            2
8     8            0            0
9     9            0            0

<ipython-input-9-a6f701c671c7>:358: RuntimeWarning:

divide by zero encountered in double_scalars

   nums  percentage
0     0           0
1     1           1
2     2           2
3     3           1
4     4           2
5     5           0
6     6           0
7     7           0
8     8           0
9     9           0

FinalStanDevx  [1, 3, 7]
FinalStanDevy  [1, 2, 3, 4, 7]
FinalRatio  [2]
Partial result[1, 2, 3, 4, 7]

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,6278.504972,-0.918218,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.25003521126760564, -0.50007042253521...","[2.473449385430855, 3.160884129134669, 3.29541...",1.499795,"[3.8454464369333854, 0.8698300316153513, 2.943...",1.931951
num1,3381.393383,6.872305,114,0.230333,"[[0.0, 0.0, 0.0, 1.5384615384615385, 3.0769230...","[[0.0, -0.31453756201275695, -0.62907512402551...","[3.049784963266647, 5.238691132958893, 2.15311...",1.636001,"[2.746543970579601, 3.44914401129788, 2.059585...",1.796055
num2,1676.442691,1.292403,90,0.819789,"[[0.0, 0.0, 0.0, 0.5136106831022086, 1.0272213...","[[0.0, -0.7474736842105264, -1.494947368421052...","[1.6080583009308191, 2.433259784891611, 2.5335...",1.920299,"[3.9373429846018437, 2.948660845394641, 0.3424...",2.634831
num3,9613.836490,0.774639,250,0.312883,"[[0.0, 0.0, 0.0, 0.39215686274509803, 0.784313...","[[0.0, -0.21782208588957055, -0.43564417177914...","[4.830404792304299, 7.337019101020188, 1.30902...",2.199275,"[0.4263084852572796, 1.2738104471726286, 3.283...",1.067535
num4,11716.298796,0.884961,290,0.464286,"[[0.0, 0.2564102564102564, 0.5128205128205128,...","[[0.0, 0.0, 0.0, 0.21133928571428573, 0.422678...","[0.2848630184542354, 0.24945598549364953, 8.23...",2.455890,"[6.384627664540635, 3.516563737333323, 0.72502...",2.605990
num5,6705.383360,-0.623297,174,0.426667,"[[0.0, -0.3125, -0.625, -0.9375, -1.25, -2.187...","[[0.0, 0.0, 0.0, 0.23670000000000002, 0.473400...","[6.994914041508794, 3.514444366347581, 1.20821...",2.046654,"[0.5966033326009739, 0.48393028723833187, 4.54...",1.712919
num6,14135.309106,-0.331703,326,0.434783,"[[0.0, -0.2857142857142857, -0.571428571428571...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.22052795031055902...","[3.1819679886215457, 4.101072765951934, 1.8475...",1.680221,"[2.1710735906793404, 3.4902293078628257, 4.474...",1.441899
num7,6557.396354,0.976741,206,0.677419,"[[0.0, 0.19047619047619047, 0.3809523809523809...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[3.8067132489376174, 3.9752522417436014, 2.619...",1.133238,"[0.0, 0.0, 0.391927981379806, 0.54915799254662...",1.720699
num8,11108.274966,-0.730253,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.298507...","[[0.0, -0.2151818181818182, -0.430363636363636...","[7.372590468793115, 5.662998276467428, 4.13002...",2.287376,"[2.362528333537912, 3.39909601984038, 6.142154...",1.334890
num9,4079.971022,-0.621717,146,0.410596,"[[0.0, 0.0, 0.0, -0.967741935483871, -1.935483...","[[0.0, -0.4702649006622517, -0.940529801324503...","[5.597181602077977, 5.652633069011466, 0.73009...",2.490486,"[0.558297487011167, 2.623974001504033, 4.28118...",2.885628

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

invalid value encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            0            0
1     1            0            0
2     2            0            1
3     3            3            1
4     4            0            2
5     5            0            0
6     6            0            0
7     7            0            2
8     8            0            0
9     9            0            0

<ipython-input-9-a6f701c671c7>:358: RuntimeWarning:

divide by zero encountered in double_scalars

   nums  percentage
0     0           0
1     1           1
2     2           1
3     3           0
4     4           1
5     5           0
6     6           0
7     7           0
8     8           0
9     9           0

127.0.0.1 - - [17/Jun/2022 17:04:38] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
FinalStanDevy  [4]
FinalRatio  [1]
Partial result[1, 4]
Final result med --> 4

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,5973.015675,-0.343808,NaN,NaN,132,0.393258,"[3.8821393479832436, 4.086346149321054, 1.1331...",1.497663,"[0.6639490962166181, 0.3689101171779015, 5.739...",2.281853,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,5973.015675,-0.343808,NaN,NaN,132,0.393258,"[3.8821393479832436, 4.086346149321054, 1.1331...",1.497663,"[0.6639490962166181, 0.3689101171779015, 5.739...",2.281853,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,5973.015675,-0.343808,NaN,NaN,132,0.393258,"[3.8821393479832436, 4.086346149321054, 1.1331...",1.497663,"[0.6639490962166181, 0.3689101171779015, 5.739...",2.281853,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,5973.015675,-0.343808,NaN,NaN,132,0.393258,"[3.8821393479832436, 4.086346149321054, 1.1331...",1.497663,"[0.6639490962166181, 0.3689101171779015, 5.739...",2.281853,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,5973.015675,-0.343808,NaN,NaN,132,0.393258,"[3.8821393479832436, 4.086346149321054, 1.1331...",1.497663,"[0.6639490962166181, 0.3689101171779015, 5.739...",2.281853,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,6884.969423,-0.641037,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.31338028169014087, -0.62676056338028...","[2.1642682122519976, 2.765773612992835, 2.8834...",1.312321,"[4.819669523828634, 1.0901967724794575, 3.6890...",2.421401
num1,2990.806577,4.797776,114,0.230333,"[[0.0, 0.0, 0.0, 1.3461538461538463, 2.6923076...","[[0.0, -0.3942239546420978, -0.788447909284195...","[2.668561842858316, 4.5838547413390325, 1.8839...",1.431501,"[3.4423660524093007, 4.322966018948195, 2.5813...",2.251075
num2,1731.840294,0.902268,90,0.819789,"[[0.0, 0.0, 0.0, 0.44940934771443247, 0.898818...","[[0.0, -0.9368421052631579, -1.873684210526315...","[1.4070510133144665, 2.1291023117801586, 2.216...",1.680262,"[4.934847565548008, 3.695688145896676, 0.42918...",3.302351
num3,10829.482327,0.540801,250,0.312883,"[[0.0, 0.0, 0.0, 0.3431372549019608, 0.6862745...","[[0.0, -0.27300613496932513, -0.54601226993865...","[4.226604193266262, 6.419891713392665, 1.14540...",1.924366,"[0.5343114376552299, 1.5965234445622298, 4.115...",1.337989
num4,12926.272335,0.617820,290,0.464286,"[[0.0, 0.22435897435897437, 0.4487179487179487...","[[0.0, 0.0, 0.0, 0.2648809523809524, 0.5297619...","[0.24925514114745598, 0.21827398730694342, 7.2...",2.148904,"[8.00213860222668, 4.407466168464522, 0.908712...",3.266204
num5,7778.146505,-0.435144,174,0.426667,"[[0.0, -0.2734375, -0.546875, -0.8203125, -1.0...","[[0.0, 0.0, 0.0, 0.2966666666666667, 0.5933333...","[6.120549786320194, 3.0751388205541335, 1.0571...",1.790823,"[0.7477495648709573, 0.6065314119731241, 5.700...",2.146878
num6,17260.455853,-0.231572,326,0.434783,"[[0.0, -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, ...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.27639751552795033...","[2.7842219900438523, 3.588438670207943, 1.6165...",1.470194,"[2.7211033596741485, 4.374460053510654, 5.6081...",1.807196
num7,7116.277578,0.681894,206,0.677419,"[[0.0, 0.16666666666666666, 0.3333333333333333...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[3.3308740928204146, 3.4783457115256513, 2.292...",0.991583,"[0.0, 0.0, 0.491220818797391, 0.68828420414940...",2.156629
num8,12620.528764,-0.509813,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.261194...","[[0.0, -0.2696969696969697, -0.539393939393939...","[6.451016660193976, 4.955123491908999, 3.61376...",2.001454,"[2.9610621276563043, 4.260238639146512, 7.6982...",1.673077
num9,4734.153736,-0.434040,146,0.410596,"[[0.0, 0.0, 0.0, -0.8467741935483872, -1.69354...","[[0.0, -0.5894039735099338, -1.178807947019867...","[4.897533901818231, 4.9460539353850335, 0.6388...",2.179175,"[0.6997391401773533, 3.288743643625671, 5.3658...",3.616686

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            2            1
1     1            0            0
2     2            0            0
3     3            0            0
4     4            0            0
5     5            8            7
6     6            8            4
7     7            0            0
8     8            5            4
9     9            2            5

   nums  percentage
0     0           1
1     1           0
2     2           0
3     3           0
4     4           0
5     5           4
6     6           4
7     7           0
8     8           2
9     9           2

127.0.0.1 - - [17/Jun/2022 17:05:02] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [5, 6, 8]
FinalStanDevy  [5, 6, 8, 9]
FinalRatio  [5, 6, 8, 9]
Partial result[5, 6, 8, 9]
Final result med --> 5

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,5041.705317,-0.123813,NaN,NaN,100,0.454545,"[1.7923448328934921, 3.9937451095431715, 1.513...",1.448581,"[1.9595917942265424, 5.573149917237109, 8.5504...",2.532638,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,5041.705317,-0.123813,NaN,NaN,100,0.454545,"[1.7923448328934921, 3.9937451095431715, 1.513...",1.448581,"[1.9595917942265424, 5.573149917237109, 8.5504...",2.532638,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,5041.705317,-0.123813,NaN,NaN,100,0.454545,"[1.7923448328934921, 3.9937451095431715, 1.513...",1.448581,"[1.9595917942265424, 5.573149917237109, 8.5504...",2.532638,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,5041.705317,-0.123813,NaN,NaN,100,0.454545,"[1.7923448328934921, 3.9937451095431715, 1.513...",1.448581,"[1.9595917942265424, 5.573149917237109, 8.5504...",2.532638,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,5041.705317,-0.123813,NaN,NaN,100,0.454545,"[1.7923448328934921, 3.9937451095431715, 1.513...",1.448581,"[1.9595917942265424, 5.573149917237109, 8.5504...",2.532638,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,6241.293619,-0.740939,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.2711267605633803, -0.542253521126760...","[2.1642682122519976, 2.765773612992835, 2.8834...",1.312321,"[4.1698264419641, 0.9432039492238007, 3.191680...",2.094920
num1,2975.108002,5.545482,114,0.230333,"[[0.0, 0.0, 0.0, 1.3461538461538463, 2.6923076...","[[0.0, -0.341070163004961, -0.682140326009922,...","[2.668561842858316, 4.5838547413390325, 1.8839...",1.431501,"[2.978226809387822, 3.7400941961686627, 2.2333...",1.947560
num2,1607.323149,1.042881,90,0.819789,"[[0.0, 0.0, 0.0, 0.44940934771443247, 0.898818...","[[0.0, -0.8105263157894737, -1.621052631578947...","[1.4070510133144665, 2.1291023117801586, 2.216...",1.680262,"[4.269474860080861, 3.1973931149892585, 0.3713...",2.857090
num3,9718.960916,0.625081,250,0.312883,"[[0.0, 0.0, 0.0, 0.3431372549019608, 0.6862745...","[[0.0, -0.2361963190184049, -0.472392638036809...","[4.226604193266262, 6.419891713392665, 1.14540...",1.924366,"[0.46226944606126635, 1.3812618565313675, 3.56...",1.157586
num4,11690.882785,0.714103,290,0.464286,"[[0.0, 0.22435897435897437, 0.4487179487179487...","[[0.0, 0.0, 0.0, 0.22916666666666666, 0.458333...","[0.24925514114745598, 0.21827398730694342, 7.2...",2.148904,"[6.923198565971397, 3.813201067098518, 0.78618...",2.825817
num5,6907.037530,-0.502958,174,0.426667,"[[0.0, -0.2734375, -0.546875, -0.8203125, -1.0...","[[0.0, 0.0, 0.0, 0.25666666666666665, 0.513333...","[6.120549786320194, 3.0751388205541335, 1.0571...",1.790823,"[0.6469293988209405, 0.5247518957520286, 4.932...",1.857411
num6,15060.340808,-0.267662,326,0.434783,"[[0.0, -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, ...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.2391304347826087,...","[2.7842219900438523, 3.588438670207943, 1.6165...",1.470194,"[2.354213019043926, 3.7846452148350593, 4.8519...",1.563529
num7,6476.737694,0.788164,206,0.677419,"[[0.0, 0.16666666666666666, 0.3333333333333333...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[3.3308740928204146, 3.4783457115256513, 2.292...",0.991583,"[0.0, 0.0, 0.42498879828538316, 0.595481839544...",1.865848
num8,11290.934636,-0.589264,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.261194...","[[0.0, -0.23333333333333334, -0.46666666666666...","[6.451016660193976, 4.955123491908999, 3.61376...",2.001454,"[2.561817795837477, 3.685824440609904, 6.66027...",1.447494
num9,4203.500101,-0.501683,146,0.410596,"[[0.0, 0.0, 0.0, -0.8467741935483872, -1.69354...","[[0.0, -0.5099337748344371, -1.019867549668874...","[4.897533901818231, 4.9460539353850335, 0.6388...",2.179175,"[0.6053922898163618, 2.845317534372772, 4.6423...",3.129043

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            5            2
1     1            0            0
2     2            0            0
3     3            0            0
4     4            0            0
5     5            5            4
6     6            6            4
7     7            0            0
8     8            3            4
9     9            2            1

   nums  percentage
0     0           0
1     1           0
2     2           0
3     3           0
4     4           0
5     5           1
6     6           2
7     7           0
8     8           2
9     9           0

127.0.0.1 - - [17/Jun/2022 17:05:07] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [0, 5, 6]
FinalStanDevy  [5, 6, 8]
FinalRatio  [6]
Partial result[6, 5, 8]
Final result med --> 6

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,1873.872995,2.03632,NaN,NaN,68,0.672031,"[1.6935334527417978, 4.086733278413076, 3.5707...",1.12629,"[0.0, 0.0, 0.4487637339278753, 0.7453559924999...",1.651382,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,1873.872995,2.03632,NaN,NaN,68,0.672031,"[1.6935334527417978, 4.086733278413076, 3.5707...",1.12629,"[0.0, 0.0, 0.4487637339278753, 0.7453559924999...",1.651382,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,1873.872995,2.03632,NaN,NaN,68,0.672031,"[1.6935334527417978, 4.086733278413076, 3.5707...",1.12629,"[0.0, 0.0, 0.4487637339278753, 0.7453559924999...",1.651382,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,1873.872995,2.03632,NaN,NaN,68,0.672031,"[1.6935334527417978, 4.086733278413076, 3.5707...",1.12629,"[0.0, 0.0, 0.4487637339278753, 0.7453559924999...",1.651382,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,1873.872995,2.03632,NaN,NaN,68,0.672031,"[1.6935334527417978, 4.086733278413076, 3.5707...",1.12629,"[0.0, 0.0, 0.4487637339278753, 0.7453559924999...",1.651382,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,6182.341558,-1.095455,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.22535211267605634, -0.45070422535211...","[2.659576451684526, 3.3987406598520526, 3.5433...",1.612655,"[3.465829769944187, 0.7839617240301715, 2.6528...",1.741232
num1,3624.615369,8.198821,114,0.230333,"[[0.0, 0.0, 0.0, 1.6542307692307692, 3.3084615...","[[0.0, -0.28348688873139616, -0.56697377746279...","[3.279281281752462, 5.6329026407140494, 2.3151...",1.759110,"[2.4754092961145533, 3.108649721490837, 1.8562...",1.618751
num2,1699.248908,1.541867,90,0.819789,"[[0.0, 0.0, 0.0, 0.5522598870056498, 1.1045197...","[[0.0, -0.6736842105263158, -1.347368421052631...","[1.729064688075863, 2.6163625837047046, 2.7242...",2.064802,"[3.5486544291581184, 2.6575734981728907, 0.308...",2.374724
num3,9327.217905,0.924163,250,0.312883,"[[0.0, 0.0, 0.0, 0.42166666666666663, 0.843333...","[[0.0, -0.19631901840490798, -0.39263803680981...","[5.193892752925198, 7.889129788371958, 1.40753...",2.364770,"[0.3842239551678059, 1.1480618028312666, 2.959...",0.962150
num4,11499.462058,1.055779,290,0.464286,"[[0.0, 0.2757051282051282, 0.5514102564102564,...","[[0.0, 0.0, 0.0, 0.19047619047619047, 0.380952...","[0.30629896059291667, 0.2682275484020467, 8.85...",2.640696,"[5.754346860028174, 3.1694138739520157, 0.6534...",2.348731
num5,6391.317548,-0.743608,174,0.426667,"[[0.0, -0.336015625, -0.67203125, -1.008046875...","[[0.0, 0.0, 0.0, 0.21333333333333335, 0.426666...","[7.52128132313233, 3.7789063049152367, 1.29912...",2.200665,"[0.5377075522667558, 0.436157419845842, 4.0993...",1.543822
num6,13004.419020,-0.395729,326,0.434783,"[[0.0, -0.3072142857142857, -0.614428571428571...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.19875776397515527...","[3.421411079765317, 4.409678491589818, 1.98652...",1.806658,"[1.9567484833611852, 3.1456791396031663, 4.032...",1.299557
num7,6492.120933,1.165275,206,0.677419,"[[0.0, 0.2048095238095238, 0.4096190476190476,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[4.093168420920173, 4.274389972934808, 2.81661...",1.218514,"[0.0, 0.0, 0.35323744273070806, 0.494945944556...",1.550834
num8,10723.371886,-0.871208,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.320970...","[[0.0, -0.19393939393939394, -0.38787878787878...","[7.927377901569798, 6.089138896771601, 4.44080...",2.459501,"[2.129303103033747, 3.0635423921952443, 5.5358...",1.203112
num9,3888.121702,-0.741723,146,0.410596,"[[0.0, 0.0, 0.0, -1.0405645161290322, -2.08112...","[[0.0, -0.423841059602649, -0.847682119205298,...","[6.018369517634345, 6.07799370745458, 0.785030...",2.677895,"[0.5031832019252878, 2.3649392493487973, 3.858...",2.600763

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

invalid value encountered in true_divide

   nums  percentagex  percentagey
0     0            0            0
1     1            3            3
2     2            6            2
3     3            1            2
4     4            1            6
5     5            0            0
6     6            0            0
7     7            8            5
8     8            0            0
9     9            0            0

<ipython-input-9-a6f701c671c7>:359: RuntimeWarning:

divide by zero encountered in double_scalars

<ipython-input-9-a6f701c671c7>:358: RuntimeWarning:

divide by zero encountered in double_scalars

<ipython-input-9-a6f701c671c7>:360: RuntimeWarning:

invalid value encountered in double_scalars

   nums  percentage
0     0           0
1     1           2
2     2           1
3     3           4
4     4           3
5     5           0
6     6           0
7     7           3
8     8           0
9     9           0

127.0.0.1 - - [17/Jun/2022 17:05:12] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [1, 2, 7]
FinalStanDevy  [1, 4, 7]
FinalRatio  [3, 4, 7]
Partial result[7, 1, 4]
Final result med --> 7

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,7676.896671,-0.389056,NaN,NaN,152,0.5,"[7.78345824310905, 4.83551674821029, 2.2435091...",2.855268,"[1.7480147469502527, 5.1114251111276845, 6.916...",2.140092,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,7676.896671,-0.389056,NaN,NaN,152,0.5,"[7.78345824310905, 4.83551674821029, 2.2435091...",2.855268,"[1.7480147469502527, 5.1114251111276845, 6.916...",2.140092,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,7676.896671,-0.389056,NaN,NaN,152,0.5,"[7.78345824310905, 4.83551674821029, 2.2435091...",2.855268,"[1.7480147469502527, 5.1114251111276845, 6.916...",2.140092,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,7676.896671,-0.389056,NaN,NaN,152,0.5,"[7.78345824310905, 4.83551674821029, 2.2435091...",2.855268,"[1.7480147469502527, 5.1114251111276845, 6.916...",2.140092,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,7676.896671,-0.389056,NaN,NaN,152,0.5,"[7.78345824310905, 4.83551674821029, 2.2435091...",2.855268,"[1.7480147469502527, 5.1114251111276845, 6.916...",2.140092,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,7729.659190,-0.815033,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.323943661971831, -0.647887323943662,...","[2.844466793245483, 3.635016748504869, 3.78972...",1.724765,"[4.982130294294768, 1.126944978293372, 3.81343...",2.503021
num1,3899.441176,6.100030,114,0.230333,"[[0.0, 0.0, 0.0, 1.7692307692307692, 3.5384615...","[[0.0, -0.407512402551382, -0.815024805102764,...","[3.507252707756644, 6.024494802902725, 2.47608...",1.881402,"[3.55840086316467, 4.468683974643078, 2.668382...",2.326954
num2,2022.765639,1.147169,90,0.819789,"[[0.0, 0.0, 0.0, 0.5906522855675398, 1.1813045...","[[0.0, -0.968421052631579, -1.936842105263158,...","[1.849267046070442, 2.798248752625352, 2.91361...",2.208344,"[5.101190741914795, 3.8202619036235306, 0.4436...",3.413666
num3,11949.916516,0.687589,250,0.312883,"[[0.0, 0.0, 0.0, 0.45098039215686275, 0.901960...","[[0.0, -0.2822085889570552, -0.564417177914110...","[5.554965511149944, 8.437571966173218, 1.50538...",2.529166,"[0.5523219355537209, 1.6503388415699454, 4.254...",1.383090
num4,14455.173842,0.785514,290,0.464286,"[[0.0, 0.2948717948717949, 0.5897435897435898,...","[[0.0, 0.0, 0.0, 0.27380952380952384, 0.547619...","[0.3275924712223707, 0.2868743833176971, 9.470...",2.824274,"[8.271873611290502, 4.556032443806023, 0.93934...",3.376300
num5,8425.693666,-0.553254,174,0.426667,"[[0.0, -0.359375, -0.71875, -1.078125, -1.4375...","[[0.0, 0.0, 0.0, 0.30666666666666664, 0.613333...","[8.044151147735112, 4.041611021299718, 1.38944...",2.353653,"[0.7729546063834613, 0.6269762910283978, 5.892...",2.219244
num6,18120.044866,-0.294428,326,0.434783,"[[0.0, -0.32857142857142857, -0.65714285714285...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.2857142857142857,...","[3.659263186914777, 4.7162336808447245, 2.1246...",1.932255,"[2.8128259448317037, 4.521913763179551, 5.7971...",1.868113
num7,8043.759106,0.866980,206,0.677419,"[[0.0, 0.21904761904761905, 0.4380952380952381...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[4.377720236278259, 4.571540078005142, 3.01242...",1.303224,"[0.0, 0.0, 0.5077788239253929, 0.7114847953005...",2.229324
num8,13850.741447,-0.648190,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.343283...","[[0.0, -0.2787878787878788, -0.557575757575757...","[8.478479039112083, 6.512448017937542, 4.74952...",2.630482,"[3.0608732106110117, 4.403842188780664, 7.9577...",1.729473
num9,5127.305233,-0.551851,146,0.410596,"[[0.0, 0.0, 0.0, -1.1129032258064515, -2.22580...","[[0.0, -0.609271523178808, -1.218543046357616,...","[6.436758842389675, 6.500528029363187, 0.83960...",2.864058,"[0.7233258527676011, 3.399600170938896, 5.5466...",3.738597

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            4            7
1     1            0            0
2     2            0            0
3     3            0            0
4     4            0            0
5     5            4            4
6     6            4            6
7     7            0            0
8     8            4            6
9     9            3            3

   nums  percentage
0     0           1
1     1           0
2     2           0
3     3           0
4     4           0
5     5           1
6     6           2
7     7           0
8     8           3
9     9           1

127.0.0.1 - - [17/Jun/2022 17:05:18] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [0, 5, 6, 8]
FinalStanDevy  [0, 6, 8]
FinalRatio  [0, 5, 6, 8, 9]
Partial result[0, 5, 6, 8]
Final result med --> 8

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3570.322009,-0.157216,NaN,NaN,126,0.506494,"[2.4448784336967666, 4.140543107156623, 1.7134...",1.647944,"[0.13819269959814165, 4.302776881141862, 5.050...",2.674354,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3570.322009,-0.157216,NaN,NaN,126,0.506494,"[2.4448784336967666, 4.140543107156623, 1.7134...",1.647944,"[0.13819269959814165, 4.302776881141862, 5.050...",2.674354,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3570.322009,-0.157216,NaN,NaN,126,0.506494,"[2.4448784336967666, 4.140543107156623, 1.7134...",1.647944,"[0.13819269959814165, 4.302776881141862, 5.050...",2.674354,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3570.322009,-0.157216,NaN,NaN,126,0.506494,"[2.4448784336967666, 4.140543107156623, 1.7134...",1.647944,"[0.13819269959814165, 4.302776881141862, 5.050...",2.674354,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,3570.322009,-0.157216,NaN,NaN,126,0.506494,"[2.4448784336967666, 4.140543107156623, 1.7134...",1.647944,"[0.13819269959814165, 4.302776881141862, 5.050...",2.674354,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,6503.053723,-0.825618,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.2711267605633803, -0.542253521126760...","[2.411613150795083, 3.0818620259063025, 3.2130...",1.462301,"[4.1698264419641, 0.9432039492238007, 3.191680...",2.094920
num1,3304.945620,6.179251,114,0.230333,"[[0.0, 0.0, 0.0, 1.5, 3.0, 3.75, 4.5, 5.25, 6....","[[0.0, -0.341070163004961, -0.682140326009922,...","[2.973540339184981, 5.10772385463492, 2.099291...",1.595101,"[2.978226809387822, 3.7400941961686627, 2.2333...",1.947560
num2,1705.494892,1.162067,90,0.819789,"[[0.0, 0.0, 0.0, 0.5007704160246533, 1.0015408...","[[0.0, -0.8105263157894737, -1.621052631578947...","[1.5678568434075486, 2.37242829026932, 2.47024...",1.872292,"[4.269474860080861, 3.1973931149892585, 0.3713...",2.857090
num3,10043.439944,0.696519,250,0.312883,"[[0.0, 0.0, 0.0, 0.38235294117647056, 0.764705...","[[0.0, -0.2361963190184049, -0.472392638036809...","[4.709644672496691, 7.153593623494684, 1.27630...",2.144293,"[0.46226944606126635, 1.3812618565313675, 3.56...",1.157586
num4,12158.546456,0.795715,290,0.464286,"[[0.0, 0.25, 0.5, 0.5, 0.5, 0.75, 1.0, 1.0, 1....","[[0.0, 0.0, 0.0, 0.22916666666666666, 0.458333...","[0.27774144299287945, 0.24321958585630832, 8.0...",2.394493,"[6.923198565971397, 3.813201067098518, 0.78618...",2.825817
num5,7073.508822,-0.560439,174,0.426667,"[[0.0, -0.3046875, -0.609375, -0.9140625, -1.2...","[[0.0, 0.0, 0.0, 0.25666666666666665, 0.513333...","[6.820041190471073, 3.4265832571888915, 1.1780...",1.995488,"[0.6469293988209405, 0.5247518957520286, 4.932...",1.857411
num6,15181.495256,-0.298252,326,0.434783,"[[0.0, -0.2785714285714286, -0.557142857142857...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.2391304347826087,...","[3.1024187889060073, 3.998545946803137, 1.8013...",1.638216,"[2.354213019043926, 3.7846452148350593, 4.8519...",1.563529
num7,6769.933060,0.878239,206,0.677419,"[[0.0, 0.18571428571428572, 0.3714285714285714...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[3.7115454177141767, 3.8758709357000116, 2.554...",1.104907,"[0.0, 0.0, 0.42498879828538316, 0.595481839544...",1.865848
num8,11637.211851,-0.656609,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.291044...","[[0.0, -0.23333333333333334, -0.46666666666666...","[7.188275707073288, 5.521423319555742, 4.02677...",2.230192,"[2.561817795837477, 3.685824440609904, 6.66027...",1.447494
num9,4304.406442,-0.559018,146,0.410596,"[[0.0, 0.0, 0.0, -0.9435483870967742, -1.88709...","[[0.0, -0.5099337748344371, -1.019867549668874...","[5.457252062026027, 5.5113172422861805, 0.7118...",2.428224,"[0.6053922898163618, 2.845317534372772, 4.6423...",3.129043

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

invalid value encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            3            3
1     1            0            0
2     2            0            0
3     3            0            0
4     4            0            0
5     5            4            3
6     6            4            4
7     7            0            0
8     8            2            5
9     9            2            2

   nums  percentage
0     0           0
1     1           0
2     2           0
3     3           0
4     4           0
5     5           0
6     6           2
7     7           0
8     8           2
9     9           1

127.0.0.1 - - [17/Jun/2022 17:05:24] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [0, 5, 6]
FinalStanDevy  [0, 5, 6, 8]
FinalRatio  [6]
Partial result[6, 0, 5, 8]
Final result med --> 6

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4081.514823,-0.204827,NaN,NaN,124,0.378947,"[3.452052529534663, 6.182833537752376, 0.47871...",2.311834,"[0.9455671431591848, 4.284176311342318, 4.9136...",2.460137,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4081.514823,-0.204827,NaN,NaN,124,0.378947,"[3.452052529534663, 6.182833537752376, 0.47871...",2.311834,"[0.9455671431591848, 4.284176311342318, 4.9136...",2.460137,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4081.514823,-0.204827,NaN,NaN,124,0.378947,"[3.452052529534663, 6.182833537752376, 0.47871...",2.311834,"[0.9455671431591848, 4.284176311342318, 4.9136...",2.460137,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4081.514823,-0.204827,NaN,NaN,124,0.378947,"[3.452052529534663, 6.182833537752376, 0.47871...",2.311834,"[0.9455671431591848, 4.284176311342318, 4.9136...",2.460137,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4081.514823,-0.204827,NaN,NaN,124,0.378947,"[3.452052529534663, 6.182833537752376, 0.47871...",2.311834,"[0.9455671431591848, 4.284176311342318, 4.9136...",2.460137,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,7272.248234,-0.617709,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.3345070422535211, -0.669014084507042...","[2.226104446887769, 2.844795716221202, 2.96587...",1.349816,"[5.144591064760901, 1.1636931841072864, 3.9377...",2.584641
num1,3081.182483,4.623180,114,0.230333,"[[0.0, 0.0, 0.0, 1.3846153846153846, 2.7692307...","[[0.0, -0.42080085046066623, -0.84160170092133...","[2.7448064669399823, 4.7148220196630035, 1.937...",1.472401,"[3.6744356739200406, 4.61440193033796, 2.75539...",2.402833
num2,1818.712426,0.869433,90,0.819789,"[[0.0, 0.0, 0.0, 0.4622496147919877, 0.9244992...","[[0.0, -1.0, -2.0, -3.5, -5.0, -7.5, -10.0, -1...","[1.4472524708377372, 2.189933806402449, 2.2802...",1.728270,"[5.267533918281582, 3.944835661350385, 0.45812...",3.524982
num3,11465.721145,0.521120,250,0.312883,"[[0.0, 0.0, 0.0, 0.35294117647058826, 0.705882...","[[0.0, -0.29141104294478526, -0.58282208588957...","[4.34736431307387, 6.603317190918172, 1.178125...",1.979347,"[0.5703324334522117, 1.704154238577661, 4.3931...",1.428191
num4,13660.840801,0.595337,290,0.464286,"[[0.0, 0.23076923076923078, 0.4615384615384615...","[[0.0, 0.0, 0.0, 0.28273809523809523, 0.565476...","[0.2563767166088119, 0.22451038694428468, 7.41...",2.210301,"[8.541608620354323, 4.7045987191475245, 0.9699...",3.486397
num5,8255.154527,-0.419308,174,0.426667,"[[0.0, -0.28125, -0.5625, -0.84375, -1.125, -1...","[[0.0, 0.0, 0.0, 0.31666666666666665, 0.633333...","[6.295422637357914, 3.1629999297128224, 1.0873...",1.841989,"[0.7981596478959656, 0.6474211700836716, 6.084...",2.291611
num6,18390.547933,-0.223145,326,0.434783,"[[0.0, -0.2571428571428571, -0.514285714285714...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.2950310559006211,...","[2.8637711897593907, 3.690965489356741, 1.6627...",1.512199,"[2.9045485299892593, 4.6693674728484496, 5.986...",1.929029
num7,7509.392024,0.657079,206,0.677419,"[[0.0, 0.17142857142857143, 0.3428571428571428...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[3.4260419240438553, 3.5777270175692415, 2.357...",1.019914,"[0.0, 0.0, 0.5243368290533948, 0.7346853864516...",2.302020
num8,13371.690797,-0.491260,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.268656...","[[0.0, -0.2878787878787879, -0.575757575757575...","[6.635331421913803, 5.0966984488206855, 3.7170...",2.058638,"[3.1606842935657182, 4.547445738414817, 8.2172...",1.785869
num9,5024.606942,-0.418245,146,0.410596,"[[0.0, 0.0, 0.0, -0.870967741935484, -1.741935...","[[0.0, -0.6291390728476821, -1.258278145695364...","[5.037463441870179, 5.08736976211032, 0.657082...",2.241437,"[0.746912565357849, 3.510456698252121, 5.72754...",3.860508

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            0            4
1     1            0            0
2     2            0            0
3     3            0            0
4     4            0            0
5     5            1            2
6     6            2            4
7     7            0            0
8     8            2            5
9     9            5            6

   nums  percentage
0     0           0
1     1           0
2     2           0
3     3           0
4     4           0
5     5           1
6     6           1
7     7           0
8     8           2
9     9           0

127.0.0.1 - - [17/Jun/2022 17:05:43] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [6, 8, 9]
FinalStanDevy  [0, 6, 8, 9]
FinalRatio  [8]
Partial result[8, 0, 6, 9]
Final result med --> 9

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4187.95111,-0.496202,NaN,NaN,118,0.641975,"[2.3749728141114783, 5.517814874724916, 2.7663...",1.533267,"[0.8528028654224418, 1.3861773347251731, 3.400...",2.913909,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4187.95111,-0.496202,NaN,NaN,118,0.641975,"[2.3749728141114783, 5.517814874724916, 2.7663...",1.533267,"[0.8528028654224418, 1.3861773347251731, 3.400...",2.913909,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4187.95111,-0.496202,NaN,NaN,118,0.641975,"[2.3749728141114783, 5.517814874724916, 2.7663...",1.533267,"[0.8528028654224418, 1.3861773347251731, 3.400...",2.913909,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4187.95111,-0.496202,NaN,NaN,118,0.641975,"[2.3749728141114783, 5.517814874724916, 2.7663...",1.533267,"[0.8528028654224418, 1.3861773347251731, 3.400...",2.913909,NaN

,Right,Ratio_xy,Width,Height,Length,Ratio_wh,StanDevx,SStanDevx,StanDevy,SStanDevy,Method
num,4187.95111,-0.496202,NaN,NaN,118,0.641975,"[2.3749728141114783, 5.517814874724916, 2.7663...",1.533267,"[0.8528028654224418, 1.3861773347251731, 3.400...",2.913909,NaN

,Right,Ratio_xy,Length,Ratio_wh,ratio_x,ratio_y,StanDevx,SStanDevx,StanDevy,SStanDevy
num0,7635.634167,-1.046462,290,0.612676,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, -0.2852112676056338, -0.570422535211267...","[3.2154842010601112, 4.10914936787507, 4.28403...",1.949734,"[4.386440802585611, 0.9922015569756858, 3.3574...",2.203747
num1,4385.313395,7.832137,114,0.230333,"[[0.0, 0.0, 0.0, 2.0, 4.0, 5.0, 6.0, 7.0, 8.0,...","[[0.0, -0.3587880935506733, -0.717576187101346...","[3.964720452246641, 6.8102984728465605, 2.7990...",2.126802,"[3.132939890394982, 3.9343848037618407, 2.3493...",2.048732
num2,2083.369794,1.472908,90,0.819789,"[[0.0, 0.0, 0.0, 0.6676938880328711, 1.3353877...","[[0.0, -0.8526315789473684, -1.705263157894736...","[2.0904757912100647, 3.163237720359094, 3.2936...",2.496389,"[4.491265761903244, 3.3634914586250644, 0.3906...",3.005511
num3,11564.552646,0.882831,250,0.312883,"[[0.0, 0.0, 0.0, 0.5098039215686274, 1.0196078...","[[0.0, -0.24846625766871167, -0.49693251533742...","[6.2795262299955885, 9.538124831326245, 1.7017...",2.859057,"[0.48628344325925427, 1.4530157192083217, 3.74...",1.217721
num4,14214.616907,1.008561,290,0.464286,"[[0.0, 0.3333333333333333, 0.6666666666666666,...","[[0.0, 0.0, 0.0, 0.24107142857142858, 0.482142...","[0.37032192399050606, 0.3242927811417444, 10.7...",3.192657,"[7.282845244723158, 4.0112894342205205, 0.8270...",2.972612
num5,7962.081033,-0.710351,174,0.426667,"[[0.0, -0.40625, -0.8125, -1.21875, -1.625, -2...","[[0.0, 0.0, 0.0, 0.27, 0.54, 0.81, 1.08, 1.08,...","[9.093388253961432, 4.568777676251855, 1.57067...",2.660651,"[0.6805361208376128, 0.5520117344923938, 5.188...",1.953900
num6,16360.989824,-0.378031,326,0.434783,"[[0.0, -0.37142857142857144, -0.74285714285714...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.2515527950310559,...","[4.1365583852080094, 5.331394595737516, 2.4017...",2.184288,"[2.476509799254, 3.981250161060257, 5.10402728...",1.644751
num7,8007.023783,1.113159,206,0.677419,"[[0.0, 0.24761904761904763, 0.4952380952380952...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[4.948727223618902, 5.167827914266682, 3.40534...",1.473209,"[0.0, 0.0, 0.4470661384560524, 0.6264159610797...",1.962775
num8,13313.250773,-0.832245,344,0.406061,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.388059...","[[0.0, -0.24545454545454545, -0.49090909090909...","[9.584367609431052, 7.361897759407655, 5.36902...",2.973589,"[2.694899239777086, 3.8772958401221063, 7.0062...",1.522688
num9,4843.941025,-0.708550,146,0.410596,"[[0.0, 0.0, 0.0, -1.2580645161290323, -2.51612...","[[0.0, -0.5364238410596026, -1.072847682119205...","[7.276336082701371, 7.348422989714907, 0.94911...",3.237631,"[0.6368412399366923, 2.9931262374570715, 4.883...",3.291591

<ipython-input-9-a6f701c671c7>:193: RuntimeWarning:

divide by zero encountered in true_divide

<ipython-input-9-a6f701c671c7>:229: RuntimeWarning:

divide by zero encountered in true_divide

   nums  percentagex  percentagey
0     0            7            8
1     1            0            0
2     2            0            0
3     3            0            0
4     4            0            0
5     5            2            4
6     6            3            4
7     7            0            0
8     8            5            4
9     9            1            4

   nums  percentage
0     0           0
1     1           0
2     2           0
3     3           0
4     4           0
5     5           2
6     6           2
7     7           0
8     8           3
9     9           2

127.0.0.1 - - [17/Jun/2022 17:05:52] "POST /_dash-update-component HTTP/1.1" 200 -

FinalStanDevx  [0, 6, 8]
FinalStanDevy  [0, 5, 6, 8, 9]
FinalRatio  [5, 6, 8, 9]
Partial result[6, 8, 0, 5, 9]
Final result med --> 0

In [8]:
# ----------------------------------------------------------------------------------------------------------------------- #
# ---------------------------------------------------- DRAW ------------------------------------------------------------- #
# ----------------------------------------------------------------------------------------------------------------------- #

# ---------------------------------------------- DRAW NUM FILTER ---------------------------------------------- #

def NTP_draw(lstx,lsty,preguiçax,preguiçay):

    fig={"coordx_dist":{},"coordy_dist":{},
           "final_distW":{},"final_distR":{},"final_dist_abs":{},
           "width":{},"height":{},"length":{},
           "ratio_wh":{},"ratio_xy":{}, "ratio_x":{},"ratio_y":{},
           "StanDevx":{},"SStanDevx":{},
           "StanDevy":{},"SStanDevy":{},
           "method":{}}

    i=int(len(lstx)/10)

    basex=lstx[0]
    basey=lsty[0]

    final_distW=[]
    final_distRx=[]
    final_distRy=[]
    ratiod_x=[]
    ratiod_y=[]
    ratio_xy=[]
    stddx=[]
    stddy=[]

    for j in range(1,11):

        fig["coordx_dist"].update({

                "coordx"+str(j)+"_"+str(j+1):lstx[(j-1)*i:j*i]

                                })

        fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)]=np.array(fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)])

        fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)]=fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)]-basex

        fig["coordy_dist"].update({

                "coordy"+str(j)+"_"+str(j+1):lsty[(j-1)*i:j*i]

                                })

        fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)]=np.array(fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)])

        fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)]=fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)]-basey

        stddx.append(np.std(fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)]))
        stddy.append(np.std(fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)]))

        final_distRx.append(sum(fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)]))
        ratiod_x.append(fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)])

        final_distRy.append(sum(fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)]))
        ratiod_y.append(fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)])

    final_distRx=np.array(final_distRx)
    final_distRy=np.array(final_distRy)
    ratiod_x=np.array(ratiod_x)
    ratiod_y=np.array(ratiod_y)

    fig["final_distR"].update({

            "num":np.sqrt((sum(final_distRx))**2+(sum(final_distRy))**2) 

        })

    fig["ratio_xy"].update({

        "num":sum(final_distRx)/sum(final_distRy)

    })

    fig["ratio_x"].update({

        "num": ratiod_x

    })

    fig["ratio_y"].update({

        "num": ratiod_y

    })

    fig["ratio_wh"].update({

        "num": preguiçax/preguiçay

    })

    fig["length"].update({

        "num": len(lsty)

        })

    fig["StanDevx"].update({

        "num": stddx

        })

    fig["SStanDevx"].update({

        "num": np.std(stddx)

        })

    fig["StanDevy"].update({

        "num": stddy

        })

    fig["SStanDevy"].update({

        "num": np.std(stddy)

        })


    data2={#"Wrong":b_fig["final_distW"],
      "Right":fig["final_distR"],"Ratio_xy":fig["ratio_xy"],
      #"Abs":b_fig["final_dist_abs"],
      "Width":fig["width"],"Height":fig["height"],
      "Length":fig["length"],"Ratio_wh":fig["ratio_wh"],
      "StanDevx":fig["StanDevx"], "SStanDevx":fig["SStanDevx"],
      "StanDevy":fig["StanDevy"], "SStanDevy":fig["SStanDevy"],
      "Method":fig["method"]}

    dfff=pd.DataFrame.from_dict(data2)
    display(dfff)
    return fig, dfff, stddx, stddy

NTP_draw(lstx,lsty,preguiçax,preguiçay)

fig=NTP_draw(lstx,lsty)[0]
dfff=NTP_draw(lstx,lsty)[1]
sttdx=NTP_draw(lstx,lsty)[2]
stddy=NTP_draw(lstx,lsty)[3]

NameError: name 'lstx' is not defined

In [9]:
# ----------------------------------------------------------------------------------------------------------------------- #
# ---------------------------------------------------- BASE ------------------------------------------------------------- #
# ----------------------------------------------------------------------------------------------------------------------- #

# ---------------------------------------------- BASE NUMS FILTER ---------------------------------------------- #

def NRP_base(fig,preguiçax,preguiçay,df,dfff,stddx,stddy,inf_limit,upper_limit):
    
    b_fig={"coordx_dist":{},"coordy_dist":{},
           "final_distW":{},"final_distR":{},"final_dist_abs":{},
           "width":{},"height":{},"length":{},
           "ratio_x":{},"ratio_y":{},"ratio_wh":{},"ratio_xy":{},
           "StanDevx":{},"SStanDevx":{},
           "StanDevy":{},"SStanDevy":{},
           "method":{}}
    
    for l in range(0,10):

        lstxx=df["x_co"][l]
        lstxx=lstxx.split(",")
        fx_lst=[float(item)for item in lstxx]

        lstyy=df["y_co"][l]
        lstyy=lstyy.split(",")
        fy_lst=[float(item)for item in lstyy]

        i=int(len(fy_lst)/10)

        b_fig["ratio_wh"].update({

                "num"+str(l): df["width"][l]/df["height"][l]

            })

        b_fig["length"].update({

                "num"+str(l): len(fy_lst)

            })

        basexx=fx_lst[0]
        baseyy=fy_lst[0]

        final_distW=[]
        final_distRx=[]
        final_distRy=[]
        ratiob_x=[]
        ratiob_y=[]
        ratio_xy=[]
        stdbx=[]
        stdby=[]


        for j in range(1,11):

     # ---------------------------------------------- X AXIS ---------------------------------------------- #

            b_fig["coordx_dist"].update({

                    "coordx"+str(j)+"_"+str(j+1):fx_lst[(j-1)*i:j*i]

                                    })

            b_fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)]=np.array(b_fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)])

            b_fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)]=b_fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)]-basexx

            #---------------------------------------------------HERE
            #----------------------------------------------------|
            #----------------------------------------------------|
            #---------------------------------------------------\/
            b_fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)]= preguiçax/df["width"][l] * b_fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)]

     # ---------------------------------------------- Y AXIS ---------------------------------------------- #

            b_fig["coordy_dist"].update({

                    "coordy"+str(j)+"_"+str(j+1):fy_lst[(j-1)*i:j*i]

                                    })

            b_fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)]=np.array(b_fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)])

            b_fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)]=b_fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)]-baseyy

            #---------------------------------------------------HERE
            #----------------------------------------------------|
            #----------------------------------------------------|
            #---------------------------------------------------\/
            b_fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)]= preguiçay/df["height"][l]*b_fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)]

     # ------------------------------------------- ANALYSIS ---------------------------------------------- #

            stdbx.append(np.std(b_fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)]))
            stdby.append(np.std(b_fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)]))

            final_distRx.append(sum(b_fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)]))
            ratiob_x.append(b_fig["coordx_dist"]["coordx"+str(j)+"_"+str(j+1)])

            final_distRy.append(sum(b_fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)]))
            ratiob_y.append(b_fig["coordy_dist"]["coordy"+str(j)+"_"+str(j+1)])

        final_distRx=np.array(final_distRx)    
        final_distRy=np.array(final_distRy) 
        ratiob_x=np.array(ratiob_x)
        ratiob_y=np.array(ratiob_y)


        b_fig["final_distR"].update({

            "num"+str(l):np.sqrt(sum(final_distRx)**2+sum(final_distRy)**2)

        })

        b_fig["ratio_xy"].update({

            "num"+str(l): sum(final_distRx) / sum(final_distRy)

        })

        b_fig["ratio_x"].update({

            "num"+str(l): ratiob_x

        })

        b_fig["ratio_y"].update({

            "num"+str(l): ratiob_y

        })

        b_fig["StanDevx"].update({

            "num"+str(l): stdbx

        })

        b_fig["SStanDevx"].update({

            "num"+str(l): np.std(stdbx)

        })

        b_fig["StanDevy"].update({

        "num"+str(l): stdby

        })

        b_fig["SStanDevy"].update({

            "num"+str(l): np.std(stdby)

        })


    data={#"Wrong":b_fig["final_distW"],
          "Right":b_fig["final_distR"],"Ratio_xy":b_fig["ratio_xy"],
          #"Abs":b_fig["final_dist_abs"],
          #"Width":b_fig["width"],"Height":b_fig["height"],
          "Length":b_fig["length"],"Ratio_wh":b_fig["ratio_wh"],
          "ratio_x":b_fig["ratio_x"], "ratio_y":b_fig["ratio_y"],
          "StanDevx":b_fig["StanDevx"], "SStanDevx":b_fig["SStanDevx"],
          "StanDevy":b_fig["StanDevy"], "SStanDevy":b_fig["SStanDevy"],
          #"Method":b_fig["method"]
         }

    dff=pd.DataFrame.from_dict(data)
    display(dff)


    # ------------------------------------------- STAN_DEV ANALYSIS ---------------------------------------------- #


    Analysis_Dx=[]
    Analysis_Dy=[]

    final_res_standevx=[]
    final_res_standevy=[]

    stddx=np.array(stddx)
    stddy=np.array(stddy)

    """print("stanDx")
    print(stddx)

    print("stanDy")
    print(stddy)"""

    for i in range(0,10):
        result=[]
        divx=stddx/np.array(dff.iloc[i]["StanDevx"])

        """print("stanB")
        print(np.array(dff.iloc[i]["StanDevx"]))
        print("num -->"+str(i))
        print(divx)"""

        if fig["ratio_xy"].get("num")>0 and dff.iloc[i]["Ratio_xy"]>0:
            for item in divx:
                if item >= inf_limit and item<=upper_limit:
                    result.append(1)

                else:
                    result.append(0)
            Analysis_Dx.append(sum(result))


        elif fig["ratio_xy"].get("num")>0 and dff.iloc[i]["Ratio_xy"]<0:
            Analysis_Dx.append(0)

        elif fig["ratio_xy"].get("num")<0 and dff.iloc[i]["Ratio_xy"]>0:
            Analysis_Dx.append(0)

        else:
            for item in divx:
                if item >= inf_limit and item<=upper_limit:
                    result.append(1)

                else:
                    result.append(0)

            Analysis_Dx.append(sum(result))


    for i in range(0,10):
        result=[]
        divy=stddy/np.array(dff.iloc[i]["StanDevy"])

        """print("stanB")
        print(np.array(dff.iloc[i]["StanDevy"]))
        print("num -->"+str(i))
        print(divy)"""

        if fig["ratio_xy"].get("num")>0 and dff.iloc[i]["Ratio_xy"]>0:
            for item in divy:
                if item >= inf_limit and item<=upper_limit:
                    result.append(1)

                else:
                    result.append(0)
            Analysis_Dy.append(sum(result))


        elif fig["ratio_xy"].get("num")>0 and dff.iloc[i]["Ratio_xy"]<0:
            Analysis_Dy.append(0)

        elif fig["ratio_xy"].get("num")<0 and dff.iloc[i]["Ratio_xy"]>0:
            Analysis_Dy.append(0)

        else:
            for item in divy:
                if item >= inf_limit and item<=upper_limit:
                    result.append(1)

                else:
                    result.append(0)

            Analysis_Dy.append(sum(result))        


    nums=[e for e in range(10)]    

    dataFd={"nums":nums, "percentagex":Analysis_Dx,"percentagey":Analysis_Dy}

    df_d=pd.DataFrame.from_dict(dataFd)
    display(df_d)

    # ------------------------------------------- STAN_DEV RES ANALYSIS ---------------------------------------------- #


    if max(Analysis_Dx)<=2:
        final_res_standevx.append(Analysis_Dx.index(max(Analysis_Dx)))

    elif sum(df_d["percentagex"].nlargest(3))>=24:
        pos_r=df_d["percentagex"].nlargest(3)

        for p in range(len(df_d)):
            if df_d.iloc[p]["percentagex"]in pos_r.values:
                #print("+24-->",df_d.iloc[p])
                final_res_standevx.append(p)

            else:
                pass

    elif sum(df_d["percentagex"].nlargest(3))<24:
        pos_r=df_d["percentagex"].nlargest(3)

        if pos_r.iloc[-1]<=2:
            pos_r.drop(pos_r.index[2])

        if pos_r.iloc[1]<=2:
            pos_r.drop(pos_r.index[1])

        for p in range(len(df_d)):
            if df_d.iloc[p]["percentagex"]in pos_r.values:
                #print("-24-->",df_d.iloc[p])
                final_res_standevx.append(p)

            else:
                pass

    if max(Analysis_Dy)<=2:
        final_res_standevy.append(Analysis_Dy.index(max(Analysis_Dy)))

    elif sum(df_d["percentagey"].nlargest(3))>=24:
        pos_r=df_d["percentagey"].nlargest(3)

        for p in range(len(df_d)):
            if df_d.iloc[p]["percentagey"]in pos_r.values:
                #print("+24-->",df_d.iloc[p])
                final_res_standevy.append(p)

            else:
                pass

    elif sum(df_d["percentagey"].nlargest(3))<24:
        pos_r=df_d["percentagey"].nlargest(3)

        if pos_r.iloc[-1]<=2:
            pos_r.drop(pos_r.index[2])

        if pos_r.iloc[1]<=2:
            pos_r.drop(pos_r.index[1])

        for p in range(len(df_d)):
            if df_d.iloc[p]["percentagey"]in pos_r.values:
                #print("-24-->",df_d.iloc[p])
                final_res_standevy.append(p)

            else:
                pass

    # ------------------------------------------- RATIO ANALYSIS ---------------------------------------------- #   


    Analysis_R=[]

    final_res_ratio=[]


    for i in range(10):

        result_p=[]

        div=fig["ratio_xy"].get("num")/dff.iloc[i]["Ratio_xy"]

        #print(div)

        if fig["ratio_xy"].get("num")>0 and dff.iloc[i]["Ratio_xy"]>0:

            #----------HERE------------------------------------------------HERE
            #-----------|---------------------------------------------------|
            #---------- |---------------------------------------------------|
            #----------\/--------------------------------------------------\/
            for l in range(10):
                divb=(preguiçax/df["width"][l]*sum(dff.iloc[i]["ratio_x"][l]))/(preguiçay/df["height"][l]*sum(dff.iloc[i]["ratio_y"][l]))
                divd=sum(fig["ratio_x"].get("num")[l])/sum(fig["ratio_y"].get("num")[l])
                div=divd/divb

                """print("Final division")
                print(div)"""

                """print("ratioB")
                print(divb)
                print("ratioD")
                print(divd)
                print("part -->"+str(i))
                print(div)"""

                if div >= inf_limit and div<=upper_limit:
                    result_p.append(1)

                else:
                    result_p.append(0)

            Analysis_R.append(sum(result_p))


        elif fig["ratio_xy"].get("num")>0 and dff.iloc[i]["Ratio_xy"]<0:
            Analysis_R.append(0)

        elif fig["ratio_xy"].get("num")<0 and dff.iloc[i]["Ratio_xy"]>0:
            Analysis_R.append(0)

        else:
            for l in range(10):

            #----------HERE------------------------------------------------HERE
            #-----------|---------------------------------------------------|
            #---------- |---------------------------------------------------|
            #----------\/--------------------------------------------------\/   
                divb=(preguiçax/df["width"][l]*sum(dff.iloc[i]["ratio_x"][l]))/(preguiçay/df["height"][l]*sum(dff.iloc[i]["ratio_y"][l]))
                divd=sum(fig["ratio_x"].get("num")[l])/sum(fig["ratio_y"].get("num")[l])
                div=divd/divb
                """print("Final division num-->"+str(i))
                print(div)"""

                """print("ratioB")
                print(divb)
                print("ratioD")
                print(divd)
                print("part -->"+str(i))
                print(div)"""

                if div >= inf_limit and div <=upper_limit:
                    result_p.append(1)

                else:
                    result_p.append(0)

            Analysis_R.append(sum(result_p))

    dataFr={"nums":nums, "percentage":Analysis_R}

    df_r=pd.DataFrame.from_dict(dataFr)

    display(df_r)

    # ------------------------------------------- RATIO_RES ANALYSIS ---------------------------------------------- #   

    if max(Analysis_R)<=2:
        final_res_ratio.append(Analysis_R.index(max(Analysis_R)))

    elif sum(df_r["percentage"].nlargest(3))>=24:
        pos_r=df_r["percentage"].nlargest(3)

        for p in range(df_r):
            if df_r.iloc[p]["percentage"]in pos_r.values:
                final_res_ratio.append(p)

            else:
                pass

    elif sum(df_r["percentage"].nlargest(3))<24:
        pos_r=df_r["percentage"].nlargest(3)
        #print(pos_r)

        if pos_r.iloc[-1]<=2:
            pos_r.drop(pos_r.index[2])

        if pos_r.iloc[1]<=2:
            pos_r.drop(pos_r.index[2])

        for p in range(len(df_r)):
            if df_r.iloc[p]["percentage"]in pos_r.values:
                final_res_ratio.append(p)

            else:
                pass


    # ------------------------------------------- FINAL RES ---------------------------------------------- #   

    partial_res=[]
    print("FinalStanDevx ",final_res_standevx)
    print("FinalStanDevy ",final_res_standevy)
    print("FinalRatio ",final_res_ratio)

    for item in final_res_standevx:
        if item in final_res_ratio:
            partial_res.append(item)
        else:
            pass

    for item in final_res_standevy:
        if item in partial_res:
            pass
        else:
            partial_res.append(item)
            pass

    print("Partial result" +str(partial_res))

    if len(partial_res)==1:
        print("Final result len 1--> "+str(partial_res[0]))


    #not the number
    elif len(partial_res)>1:
        answer=[(Analysis_R[partial_res[l]]+Analysis_Dx[partial_res[l]]+Analysis_Dy[partial_res[l]])/2 for l in range(len(partial_res))]
        #print("Answer"+str(answer))
        if answer.count(max(answer))>1:
            inf_limit+=0.2
            upper_limit-=0.2
            NRP_base(fig,preguiçax,preguiçay,df,dfff,stddx,stddy,inf_limit,upper_limit)
            
        else:
            print("Final result med --> "+str(partial_res[answer.index(max(answer))]))




    else:
        lista=[max(Analysis_R),max(Analysis_Dx),max(Analysis_Dy)]
        if lista.index(max(lista)) == 0:
            print("Final result--> "+str(max(final_res_ratio)))

        elif lista.index(max(lista)) == 1:
            print("Final result--> "+str(max(final_res_standevx)))

        else:
            print("Final result--> "+str(max(final_res_standevy)))
            
    return "hehe"

NRP_base(fig,preguiçax,preguiçay,df,dfff,stddx,stddy,inf_limit,upper_limit)

NameError: name 'fig' is not defined

In [14]:
print(dff.iloc[1]["ratio_x"][7])
print(dff.iloc[1]["ratio_y"][7])
print(dff.iloc[1]["StanDev"][7])

[61.51515152 61.51515152 61.51515152 61.51515152 61.51515152 61.51515152
 61.51515152 61.51515152 61.51515152 61.51515152 61.51515152 61.51515152
 61.51515152 61.51515152 62.57575758 63.63636364 63.63636364 63.63636364
 63.63636364 63.63636364 63.63636364]
[16.86776269 17.49249464 18.11722659 18.74195854 19.36669049 19.99142244
 20.6161544  21.24088635 21.8656183  22.49035025 23.1150822  23.73981415
 24.3645461  24.98927806 25.61401001 26.23874196 27.17583989 28.11293781
 28.73766976 29.36240172 29.98713367]
0.9529273870764228

In [1]:
!env:FLASK_APP = "S2FinalProject.ipynb"
!env:FLASK_ENV = "development"
!flask run

A sintaxe do nome do arquivo, do nome do diret¢rio ou do r¢tulo do volume est  incorreta.
A sintaxe do nome do arquivo, do nome do diret¢rio ou do r¢tulo do volume est  incorreta.

 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

Usage: flask run [OPTIONS]

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

In [2]:
df=pd.read_excel(r"C:\Users\adm\Documents\Jupyter\Semestre2\Programação\assets\numbers_base.xlsx")
df=df[["numb","height","width","x_co","y_co"]]
display(df)

,numb,height,width,x_co,y_co
0,0,142.00,87.00,"111.421875, 111.421875, 111.421875, 111.421875...","63.25, 62.75, 62.25, 61.75, 61.25, 60.75, 60.2..."
1,1,112.88,26.00,"55.34375, 55.34375, 55.34375, 56.34375, 57.343...","64.78125, 64.28125, 63.78125, 62.28125, 60.781..."
2,2,95.00,77.88,"39.34375, 39.34375, 39.34375, 40.34375, 41.343...","76.78125, 75.78125, 74.78125, 73.28125, 71.781..."
3,3,163.00,51.00,"50.421875, 50.421875, 50.421875, 50.921875, 51...","19.25, 18.75, 18.25, 18.25, 18.25, 18.25, 18.2..."
4,4,168.00,78.00,"31.421875, 31.921875, 32.421875, 32.421875, 32...","11.25, 11.25, 11.25, 11.75, 12.25, 13.75, 15.2..."
5,5,150.00,64.00,"107.421875, 106.921875, 106.421875, 105.921875...","19.25, 19.25, 19.25, 19.75, 20.25, 20.75, 21.2..."
6,6,161.00,70.00,"101.421875, 100.921875, 100.421875, 99.921875,...","11.25, 11.25, 11.25, 11.25, 11.25, 11.75, 12.2..."
7,7,155.00,105.00,"31.421875, 31.921875, 32.421875, 32.921875, 33...","21.25, 21.25, 21.25, 21.25, 21.25, 21.25, 21.2..."
8,8,165.00,67.00,"102.59375, 102.59375, 102.59375, 102.59375, 10...","29.375, 28.875, 28.375, 27.875, 27.375, 26.875..."
9,9,151.00,62.00,"101.421875, 101.421875, 101.421875, 99.921875,...","17.25, 16.25, 15.25, 14.75, 14.25, 14.25, 14.2..."

In [7]:
l=[1,2,3,4,5,6,7]
l=np.array(l)

j=[8,9,10,11,12,13,14]
j=np.array(j)

k=[j,l]
k=np.array(k)

m=[80,90,100,110,120,130,140]
m=np.array(m)

n=[10,20,30,40,50,60,70]
n=np.array(n)

p=[m,n]
p=np.array(p)

#print(sum(k))
print(len(Analysis_D))

10